### ISSUE TITLE
Allow multiple globals_patterns on TemplatedConfigLoader

### ISSUE THREAD

**Issue by ppsimatikasmck** [kedro-org/kedro#1210]
## Description

It would be great if we could pass a list of patterns in the constructor: https://github.com/kedro-org/kedro/blob/e78990c6b606a27830f0d502afa0f639c0830950/kedro/config/templated_config.py#L99 

## Context

We do have our global parameters into different subfolders with different names, why not allow multiple patterns here?

## Possible Implementation

Alter this constructor to this: https://github.com/kedro-org/kedro/blob/e78990c6b606a27830f0d502afa0f639c0830950/kedro/config/templated_config.py#L95

To this:

```python
def __init__(
        self,
        conf_paths: Union[str, Iterable[str]],
        *,
        globals_pattern: Optional[str] = None,
        globals_dict: Optional[Dict[str, Any]] = None,
        globals_patterns: Optional[List[str]] = None,
):
    """Instantiate a ``TemplatedConfigLoader``.
    Args:
        conf_paths: Non-empty path or list of paths to configuration
            directories.
        globals_pattern: Optional keyword-only argument specifying a glob
            pattern. Files that match the pattern will be loaded as a
            formatting dictionary.
        globals_dict: Optional keyword-only argument specifying a formatting
            dictionary. This dictionary will get merged with the globals dictionary
            obtained from the globals_pattern. In case of duplicate keys, the
            ``globals_dict`` keys take precedence.
        globals_patterns: Optional list of keyword-only arguments specifying multiple glob
            patterns. Files that match the pattern will be loaded as a
            formatting dictionary.
    """

    super().__init__(conf_paths)

    patterns = deepcopy(globals_patterns) or []

    if globals_pattern:
        patterns.append(globals_pattern)

    self._arg_dict = super().get(*globals_patterns) if globals_patterns else {}
    globals_dict = deepcopy(globals_dict) or {}
    self._arg_dict = {**self._arg_dict, **globals_dict}
```

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by AntonyMilneQB** [comment]
Hi @ppsimatikasmck, this is a very reasonable point given that elsewhere we typically accept multiple patterns rather than just one. I don't think your suggestions implementation of two `globals_pattern` and `globals_patterns` arguments is going to be the right solution here though (even though it would be backwards compatible, which is definitely a good thing).

Actually now that I look at the code I don't see why it shouldn't work already with `global_pattern` being a list rather than a single string. The `get` method already accepts `*patterns`, and so I think you can actually _already_ pass a list into `globals_pattern` and it will work as you want it to. All we should need to do is to change the type hint (and arguably, the name of the argument should have an `s` on the end... but that would be an annoying breaking change).

Please do try and just put a list into `global_pattern` and see if it already works and let me know 🙂

**Comment by noklam** [comment]
I think this is now tracked by #1363.

**Comment by MerelTheisenQB** [comment]
Closing this ticket in favour of https://github.com/kedro-org/kedro/issues/1363. @ppsimatikasmck please do add any comments there if you have more ideas about this feature 🙂
