### ISSUE TITLE
Update black to a non pre-release version (black==22.1.0)

### ISSUE THREAD

**Issue by Galileo-Galilei** [kedro-org/kedro#1327]
## Description

The kedro template still use [``black==21.5b1``](https://github.com/kedro-org/kedro/blob/b573594bf1b1df8f73f345673db3a0224df0a634/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/requirements.txt#L1) which is a pre-release version non covered by [the stability policy](https://black.readthedocs.io/en/latest/the_black_code_style/index.html#stability-policy) of the last [22.1.0 version](https://github.com/psf/black/releases/tag/22.1.0).

## Context

I would like to be able to install a non prelease version of black and to benefit for their stability policy. I also think it is better for kedro not to rely on a pre-release version if an official release is available (e.g. to avoid warning from internal security tools).

## Possible Implementation

- Change to ``black==22.1.0`` in the template requirements
- Update the files of the template with the new black version (a couples of files have some lines splitted differently). This is completely straightforward.

Unless I miss something which would have some other impact, I can open a PR.

## Possible Alternatives

Let people change the black version themselves in their templates. Since click was upgraded in #1193 , this will be possible in ``kedro=0.18``. I do not really like this option (you have to remember to do this each time you start a kedro project + you have a first commit with pure formatting change which is less readable) but this would be a possible workaround.

**Comment by AntonyMilneQB** [comment]
Hi @Galileo-Galilei, thanks for pointing this out. Your proposed solution sounds good - please do go ahead and open a PR. If you don't mind raising one for https://github.com/kedro-org/kedro-starters also then that would be great also. Since the click requirement has only been bumped for `develop`, I presume the black version change will only work in kedro 0.18? In which case you should make the kedro-starters PR's target branch = 0.18.0.

Somewhat related - interested in your thoughts on https://github.com/kedro-org/kedro/issues/1293 if you get a chance to look at it. And also I finally got around to thinking about [this](https://github.com/kedro-org/kedro/issues/1041) and I think you will like the result 😄

**Comment by Galileo-Galilei** [comment]
Thank you, I've done it for the main repo and I'll do it for the starters soon. I am quite busy right now but I've seen your reply on above thread (thank you for this!) and will answer as soon as i can.
