### ISSUE TITLE
Make config glob paths configurable by the user

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro#1363]
## Description
>Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Fix #1210 

Today catalog config is loaded via the following paths (this also applies the same to parameters):
```python
conf_catalog = conf_loader.get('catalog*', 'catalog*/**')
```
https://github.com/kedro-org/kedro/blob/e78990c6b606a27830f0d502afa0f639c0830950/kedro/framework/context/context.py#L356

These are hardcoded in the library and the user of a project cannot change without getting creative. I think there would be a lot of user value (1) making these configurable (2) being transparent with how this works.

## Context
> Why is this change important to you? How would you use it? How can it benefit other users?

* It feels restrictive to stop users controlling this when so much of the framework is configurable
* We have evidence of users want to do `_catalog` suffixes (as opposed to prefixes) which aren't supported by the default pattern

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

* In 0.18.x it may make sense to expose in `settings.py`

**Comment by MerelTheisenQB** [comment]
Wouldn't this be possible by using a custom `ConfigLoader`, which the users can do in `settings.py` from `0.18.0`?

**Comment by idanov** [comment]
@datajoely As @MerelTheisenQB pointed out, this is already configurable through a custom `ConfigLoader` in `settings.py`, so closing the issue.

**Comment by datajoely** [comment]
So I actually disagree here - I think it's highly likely that a novice user would like to control this without the added complexity of the creating a custom class. 

The smallest version of this I can imagine involves inheriting from the config loader you were already using, and overriding `_get_config_credentials(self)`  and the `params(self)` which is type `@property`. I really think this is prohibitively complex for novices.

What about adding the defaults as constructor arguments?

**Comment by yetudada** [comment]
I have a query, why do users want `_catalog` suffixes and how many users does this affect?

**Comment by AntonyMilneQB** [comment]
I actually think this isn't at all configurable as it currently stands through making a custom config loader. Since the calls like `config_loader.get("catalog*", "catalog*/**", "**/catalog*")` are buried inside context.py, as Joel points out you would actually need to make a custom `KedroContext` to change these, and even then they're not easy to change.

As a first step I think it's a very good idea to make these methods easier to override by a user writing a custom `KedroContext`. When we refactored the `ConfigLoader` we deliberately exposed some methods like [`_build_conf_paths` ](https://github.com/kedro-org/kedro/blob/develop/kedro/config/config.py#L103) so that users can easily modify them. I think we should do the same for `_get_catalog_path`, `_get_params_path`, etc. in `KedroContext`. These are easy changes to make and make kedro easier to understand and more extensible.

**Comment by DebanjanBanerjeeQB** [comment]
Was chatting with @datajoely on our slack , we have client folks who are building pipelines on kedro for the first time (many of them) . There was a guy who built a very small pipeline on first go and the only error he was getting was because he named the catalogs like `raw_catalog.yml` instead of `catalog_raw.yml`. 

If you think of it both names make right amount of sense and i could not find an argument on why the former is wrong and the latter is incorrect. Ideally we can make it configurable with only `*catalog*` to be present in the YAML filename that tells Kedro where to look. Also , agree with Joel , we are talking about client DEs who before 2 months ago were building drag and drop pipelines on informatica and people who used to maintain codebases on shared folders :) so not sure how much we can ask them to look into a custom `ConfigLoader` for a very small naming convention challenge.

WDYT ?

**Comment by DebanjanBanerjeeQB** [comment]
Basis the above discussion , do we see a benefit in reopening and working on this issue ? Let me know thx!

**Comment by MerelTheisenQB** [comment]
This was done in https://github.com/kedro-org/kedro/pull/1870 and https://github.com/kedro-org/kedro/issues/1864. Docs will be added in https://github.com/kedro-org/kedro/issues/1462
