### ISSUE TITLE
Reduce Kedro package size by removing the docs from kedro

### ISSUE THREAD

**Issue by nraw** [kedro-org/kedro#1410]
## Description

The kedro wheel is 87MB big. Kedro is 114MB big on disk. Most of that (112MB) is assets used for the website framework, like for example 70MB of images. 

## Context
Fast installation means shorter cicd loops. Small disk usage means easier for edge devices.

## Possible Implementation
Do you think it might be worth splitting the site away from the core library, so that installation and disk space get reduced drastically?

**Comment by AntonyMilneQB** [comment]
+💯  for this. Kedro 0.18 is now 112MB unpackaged, 111MB is just docs.

Just to give some context: the reason that the docs are part of the package is because historically there were instances where people were using locked down environments in which they could `pip install kedro` but didn't have access to kedro documentation online. Hence shipping the docs with kedro and using the `kedro docs` command to display them.

However, I strongly suspect that very few people are in this situation. Unfortunately it's difficult to prove this through telemetry data, since those who can't access kedro docs online and are therefore using `kedro docs` are also unlikely to be able to send us telemetry data...  Maybe in the past when the docs were smaller it was ok to include them but as you say it now _massively_ bloats the package size. When I `pip install kedro` and/or project requirements, it is now quite striking just how long it takes to download kedro compared to other packages. kedro should absolutely not be comparable to tensorflow in package size, and packaging documentation in this way does not seem to be normal for other Python packages.

So yeah, even if `kedro docs` is still useful for a few users I would definitely favour removing it since the vast majority of users would benefit from this.

**Comment by datajoely** [comment]
I would also say the `kedro docs` command had a lot more value when it was closed source. Maybe we should just alias the command to open the browser and point to http://kedro.readthedocs.io/?

**Comment by deepyaman** [comment]
Create a `kedro-docs` package and make it an extra installable as `kedro[docs]`, for people who really need the `kedro docs` functionality? I, for one, didn't realize it existed. 😅

**Comment by idanov** [comment]
After a discussion within the team we decided that we'll remove the docs from the package and repurpose the command `kedro docs` to redirect you to ReadTheDocs with a message explaining that from 0.18.1 `kedro docs` is deprecated and will not be available from 0.19.0.
