### ISSUE TITLE
Update all starters to install `kedro-datasets[xxxxx]` instead of `kedro[xxxx]`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1495]
Also update any starter docs that still mention `kedro[XXX]`

**Comment by MerelTheisenQB** [comment]
Notes from **Technical Design session** 20/7:

### Discussion 
We'll be implementing a [redirect from `pip install kedro[xxx]` to `pip install kedro-datasets[xxx]`.
](https://github.com/kedro-org/kedro/issues/1496) The question we discussed is whether we still want to mention and use `pip install kedro-datasets[xxx]`. Some of the points that were brought up are as follows:

- `pip install kedro[xxx]` should be the advised way to install datasets, because inside Kedro `kedro-datasets` will be pinned and thus the user would always be installing a supported version of the dataset with the Kedro version they are using. When they install directly from `kedro-datasets` they will be able to user newer dataset versions, but these could potentially break with other Kedro functionality if support hasn't been added yet.
- Extra_requires would be pinned to e.g. Kedro-datasets ~= 1.0, and can also specify the python version
- `pip install kedro[pandasCSV]` will look for latests compatible `kedro-datasets` version
- A counter argument to only using `pip install kedro[xxx]` was that release frequency will be different between `kedro` and `kedro-datasets` and so if hypothetically `kedro-datasets` would get a lot of breaking released users wouldn't be able to benefit directly from those. Arguably, the release frequency wouldn't be so different (e.g we wouldn't end up with `kedro-datasets` `4.0` from `1.0` within 2 months when `kedro` would only have gone from `0.18.2` to `0.18.4`) 
- What would we do with the CCI builds for `kedro-datasets` if a dataset would break the CI for a newer python version -> just skip that dataset for that specific python version so we can still release

### Conclusion
Since we're adding the redirect from `pip install kedro[xxx]` to `pip install kedro-datasets[xxx]` we will use and encourage users to use `pip install kedro[xxx]` to ensure they use dataset versions that are compatible with the installed version of Kedro. Therefore, we won't need to update the starters and/or documentation. 

Users who want a newer dataset version could still do `pip install kedro-datasets[xxx]`, but they would have to deal with any consequences that this newer dataset might have on the functioning of Kedro.

**Comment by jmholzer** [comment]
Is there a rule for specifying which version of `kedro-datasets` should be used, based on the version of `kedro`? If not, should it always be the latest?

**Comment by jmholzer** [comment]
At the moment, `pip install "kedro[pandas.CSVDataSet]"` and `pip install "kedro-datasets[pandas.CSVDataSet]"` install a different set of dependencies. It seems as though the latter is installing all the requirements for every dataset. I will raise this and present my findings in a new issue.
