### ISSUE TITLE
Fix Windows, Python 3.10 CI

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro#1517]
`win_pip_compile-3.10` and `win_unit_tests-3.10` are failing on the "Install all requirements" stage with no useful error message.

Weirdly this seemed to be magically fixed in https://github.com/kedro-org/kedro/pull/1507 (see build for [70419d2](https://github.com/kedro-org/kedro/pull/1507/commits/70419d27a47e812ae49d667fd8a408b4e8f206ac)) but then the merge commit to main with exactly the same code didn't work (https://github.com/kedro-org/kedro/commit/7c492031307831716855c8a1e9efbe973d885439). So there's something non-deterministic going on here.

I originally thought this was related to the fiona issue explained in https://github.com/kedro-org/kedro/issues/1377, but that was actually unit tests rather than requirements installation failing. So I think this is something different.

**Comment by SajidAlamQB** [comment]
Restoring the conda environment via the cache seems to cause dependency conflicts with the `install GDAL, Fiona and pytables` step breaking the environment. 

So, the reason why build [70419d2](https://github.com/kedro-org/kedro/pull/1507/commits/70419d27a47e812ae49d667fd8a408b4e8f206ac)) passed while https://github.com/kedro-org/kedro/commit/7c492031307831716855c8a1e9efbe973d885439 didn't is because the former didn't have a cache hit so there was no restore of the conda environment while the latter did.

**Comment by AntonyMilneQB** [comment]
Ah yes, very nice detective work @SajidAlamQB! That makes sense about it working whenever we change the requirements file because it doesn't restore a cache then. Good to have that mystery resolved rather than it just seeming random 🎉
