### ISSUE TITLE
Feature: make AbstractDataset take data type as generic parameter.

### ISSUE THREAD

**Issue by shaunc** [kedro-org/kedro#1564]
## Description

Abstract dataset is currently incompletely typed, as _load and _save use "Any".

## Context

I would like to write typed code.

## Possible Implementation

Use:
```
class AbstractDataset(Generic[DS]): ...
```
If necessary for deprecation, could have something like:
```
class BaseDataset(Generic[DS]): ...

class AbstractDataset(BaseDataset[Any]): ...
```
and deprecate `AbstractDataset` in favor of `BaseDataset`.

**Comment by AntonyMilneQB** [comment]
Hi @shaunc, thanks very much for the suggestion! This sounds like a very good idea, but I'm not quite sure how you would intend to use it in practice? Are you just suggesting that we add the `Generic` to `AbstractDataset` inheritance + `_load` + `_save` methods or are there other changes involved here also?

Also, `AbstractDataSet` currently inherits from `abc.ABC`. As far as I can tell there's no reason we shouldn't just do this?
```
class AbstractDataSet(abc.ABC, Generic[DS]):
```

As far as I can tell, there's nothing at all breaking about this change and all datasets will continue to function exactly as they currently do. So I don't see any need to do it in two stages and have a new `BaseDataSet`. Or am I missing something here? Can adding `Generic[DS]` to the inheritance actually break anything for anyone?

**Comment by shaunc** [comment]
Everything "runtime" should work exactly the same. Users who type check, however, will have to use `AbstractDataSet[Foo]` or `AbstractDataSet[Any]` in code where they currently just use `AbstractDataSet` ... from mypy perspective (but not that of your test suite, presumably) it would be a "breaking change".

If I were them (that is, such a user), I would be happy, of course.... I suggested that "just in case".

NB -- e.g. your various derived classes will have to be changed as well. I guess in a few cases you'll want to use `Union[ ... ]`s or pass through the generic for types that accept various formats for saving. One developer should be able to make the changes quickly just by tracking down the places that mypy points at....

**Comment by AntonyMilneQB** [comment]
Cool, thanks for the explanation. I think this is fine to regard as non-breaking since it's only type-checking rather than actual execution. It will only affect a tiny fraction of users anyway, so I will take you as a representative when you say that it would make such users happy 😀  So long as we add something to the release notes about the change I think we're good here.

So please do go ahead and raise a PR for this, since in all honesty we're not going to do it ourselves 😅  Our type hints could do with improvements all round but it's not a priority really.

Two things I don't quite understand here I hope you can explain.

1. "NB -- e.g. your various derived classes will have to be changed as well". I just tried `class AbstractDataSet(abc.ABC, Generic[DS])` and running mypy and it didn't trigger any messages about our datasets that inherit from `AbstractDataSet`. Would you expect it to?
2. The only way we use mypy currently is [this pre-commit hook](https://github.com/kedro-org/kedro/blob/main/.pre-commit-config.yaml#L31-L41). When I run it on all files there's no errors returned and it also runs on CI without showing anything. I'm pretty sure there are lots of problems though, and indeed when I run `mypy` from the command line with the same options it shows them. Do you know why the pre-commit hook isn't flagging them?
