### ISSUE TITLE
Security issue with cookiecutter<2.1.1

### ISSUE THREAD

**Issue by Galileo-Galilei** [kedro-org/kedro#1600]
## Description
Snyk is complaining about a security issue with the ``cookiecutter``  (1.7.0) used in kedro. I don't know if it is valid or not, but it breaks my CI workflow when installing kedro. 

![image](https://user-images.githubusercontent.com/29451317/172691589-46fdd78d-e188-43ed-8cef-40ccbbe92cb3.png)
 

## Context

``kedro`` cannot be installed in an enterprise context, and my [kedro-mlflow CI](https://github.com/Galileo-Galilei/kedro-mlflow/pull/327) complains. This impacts all kedro versions. 

## Other remarks

I haven't seen a specific process to warn about potential security issues, but it does not feel right to open a public github issue though, did I miss something there? This one does not seem too big a threat (and snyk warns publicly about it), so I choose to report it there.

**Comment by deepyaman** [comment]
> I don't know if it is valid or not

I think it's valid! In short, https://github.com/kedro-org/kedro/blob/686dba54775ddc7a1ddaef5481e3b82717d33b0f/kedro/framework/cli/starters.py#L263 traces back to https://github.com/cookiecutter/cookiecutter/blob/2.1.1/cookiecutter/vcs.py#L57, which was fixed to address the exploit in v2.1.1.

**Comment by AntonyMilneQB** [comment]
It's a bad vulnerability but realistically I don't think this will affect many people using kedro because it only exists for mercurial repos (rather than git), which I think are never used in this community. We should definitely bump to the fixed cookiecutter version, but just to put people's minds at ease.

> I haven't seen a specific process to warn about potential security issues, but it does not feel right to open a public github issue though, did I miss something there? This one does not seem too big a threat (and snyk warns publicly about it), so I choose to report it there.

You didn't miss anything: there is no such process. Vulnerabilities that are public knowledge are fine to report here. AFAIK  we've never had a security issue in kedro itself that wasn't one of our dependencies, but if it does happen then I guess a private message on discord or email would be better than a github issue?

I'm surprised our own snyk checks didn't pick this up actually. @MerelTheisenQB do those still run?

**Comment by MerelTheisenQB** [comment]
> I'm surprised our own snyk checks didn't pick this up actually. @MerelTheisenQB do those still run?

With the move to the new `kedro-org` and the linux foundation, the Snyk setup was actually never fully setup because it's not clear if it needs to run on QB or Linux Foundation infra. @yetudada reached out to the Linux Foundation people, but I'm not sure they ever got back about this topic?
