### ISSUE TITLE
Not possible to have no `logging.yml` with custom `CONF_SOURCE` on Databricks

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1615]
## Description
Using the latest logging setup from `main` it seems that it's not possible to not have `logging.yml` when having set a custom `CONF_SOURCE` in `settings.py` on Databricks. 

## Context
Databricks initially throwed errors about being a read-only system, but the new logging setup is supposed to fix this. 
@avan-sh has a setup where the `conf` folder is located in `src/project`  with updated `settings.py`:

```
from pathlib import Path
CONF_SOURCE = Path(__file__).parent / "conf"
```
This works with the new logging setup as long has the `logging.yml` file **is not deleted**. If it's deleted the following error is thrown:
![Screenshot 2022-06-14 at 7 11 53 PM](https://user-images.githubusercontent.com/49397448/173566723-2ffa4404-3ef5-4293-b25f-0b81d3a66906.png)

The above setup works fine locally, but not on Databricks. 

## Steps to Reproduce: All of this needs to be done on Databricks
1. Install kedro from `main`
2. Create a new kedro project
3. Move `conf` folder into `src/project`
4. Update `settings.py` with: 
```
from pathlib import Path
CONF_SOURCE = Path(__file__).parent / "conf"
```
5. `kedro run` will be successful 
6. Remove `logging.yml`
7. `kedro run` will throw the above error

## Expected Result
`kedro run` should run successfully if there's no `logging.yml` file present. 

## Actual Result
Error is thrown about not finding a `logging.yml` file

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro from `main`
* Python version used (`python -V`):
* Operating system and version: Databricks

**Comment by AntonyMilneQB** [comment]
@avan-sh I strongly suspect this is just because you do not in fact have the latest `main` branch installed correctly on databricks. The easiest way to check this would be to just do `cat `/path/to/site-packages/kedro/framework/session/session.py` and compare to our one in main: https://github.com/kedro-org/kedro/blob/main/kedro/framework/session/session.py

Note that the one in main has a `try/except` which specifically catches this exception:
https://github.com/kedro-org/kedro/blob/main/kedro/framework/session/session.py#L185-L195

`pip install`ing things on databricks directly from within a notebook can be tricky but the general rule seems to be that `%pip install` is safer than `%sh pip`. These two things do not necessarily install to the same place!

**Comment by avan-sh** [comment]
It is very likely to be a environment issue as suggested by @AntonyMilneQB. On a clean reinstall, I didn't face any error and worked as expected.

This issue can be closed now. Thanks a lot for your help @MerelTheisenQB & @AntonyMilneQB :)
