### ISSUE TITLE
KedroSession: getpass.getuser() call fails

### ISSUE THREAD

**Issue by naikio** [kedro-org/kedro#1624]
## Description
First of all, I want to thank you for this splendid work that is Kedro. I believe it makes our life easier and I am glad that we have adopted it at my company.
This is the first time that I post an issue here, so I hope to frame this correctly!

In my company, we are using Kedro pipelines orchestrated in Airflow (we don't use kedro-airflow but we have a custom setup).
I have recently upgraded one pipeline to Kedro 0.18, but it's currently failing here:

```
# Line 167 of kedro/framework/session/session.py
session_data["username"] = getpass.getuser()
```

with the following error:
``KeyError: 'getpwuid(): uid not found: 1000``

I believe this is due to this process running with an uid that is not defined in /etc/passwd.
I am not super familiar with this things, but googling, it seems this is not an uncommon situation when using existing images.

Maybe it might be better to wrap that line in a try/except clause and catch ImportErrors?
This username tag does not seem to serve a critical purpose so I think the code should not crash because of this.

Right now I have solved it temporarily by setting an environment variable (USERNAME). What do you think?

## Steps to Reproduce
1. Run Kedro pipeline in a containerized setting with a UID that does not exist in /etc/passwd

## Expected Result
I expect that the code runs fine, and maybe the KedroSession is initialized with a "none" user or something like that

## Actual Result
The code crashes with a KeyError when setting username in KedroSession

## Your Environment
Our custom Docker Image is ultimately based on python:3.8-buster:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.1
* Python version used (`python -V`): 3.8
* Operating system and version: Code running in Airflow on a custom image based on python:3.8-buster

**Comment by AntonyMilneQB** [comment]
Hello @naikio and thank you for your comments! Very pleased to hear that kedro makes your life easier 🙂 Do you mind me asking what your company is?

Thanks for the very clear bug report. You're right that that this `username` isn't currently used anywhere, and your current workaround of setting `USERNAME` in an environment variable is definitely a good one.

The username destined to appear on the experiment tracking screen in kedro-viz but doesn't seem to have quite made it there yet (see recently opened https://github.com/kedro-org/kedro-viz/issues/911). I was actually considering adding `getpass.getuser` to our code so I'm very surprised to see that it's already there! Your bug report is remarkably timely 😀 

I'm actually also surprised that that this is the first time we've heard about this problem since this line of code will have been executed A LOT on lots of different machines (it's run every time anyone does a `kedro run`). I'm not a devops person but I would be curious to know if your situation of not having uid defined in `/etc/passwd` is therefore quite unusual or not quite right in some way, even if it's a problem you've seen discussed in other contexts online?

Either way, you're absolutely right that kedro should not crash in such a scenario and we should wrap the call in a `try/except`. If you get a chance please feel free to raise a PR that does this - otherwise I'll add it to our backlog.
