### ISSUE TITLE
Add a feature to allow user customize CLOUD_PROTOCOLS when developing new fsspec protocols

### ISSUE THREAD

**Issue by Felipeasg** [kedro-org/kedro#1632]
## Description
Is a little bit boring stay editing kedro [source code](https://github.com/kedro-org/kedro/blob/main/kedro/io/core.py#L31) when developing new protocols to different storage media. This list of `CLOUD_PROTOCOLS` could be defined in a declarative format or using some API to extend the list of available protocols.

## Context
When you are developing new protocols extending **fsspec** **AbstractFileSystem** to another storage media, is interesting add a simple way to add the protocol in kedro framework. 
This will avoid the change in the list of `CLOUD_PROTOCOLS` be overridden  always when you reinstall kedro to update version or create a new virtual environment.

## Possible Implementation
- Create a API function to be called that add new protocol in `CLOUD_PROTOCOLS` list (e.g. `add_new_cloud_protocol('some_protocol')`

**Comment by AntonyMilneQB** [comment]
To do:
- [ ] work out whether we can go back to using fsspec's own `infer_storage_options` or not
- [ ] if yes: go back to using it. Remove `CLOUD_PROTOCOLS` (technically breaking and should only be done in `develop` if we think anyone might be using it)
- [ ] if no: figure out which protocols we're missing from fsspec and add them to `CLOUD_PROTOCOLS`

**Comment by Felipeasg** [comment]
Hi Antony,

Thanks by your answer, really `fsspec` already have `infer_storage_options` and seems that kedro is duplicating this functionality, but if I understood well the `CLOUD_PROTOCOLS` and parser was inserted to avoid problems due strange behavior with old implementations of `fsspec` parser.

Really I agree add a python entry point to add new protocols could be a overkill.

Today we avoid problems with new installations of kedro using something like bellow, but we are not comfortable with it:
```shell
# Add a manual entry on Kedro IO protocols
# Look for Gdrive in Protocols
j=`grep gdrive -c $kedro_io`
if [ $j -eq 0 ]; then
    echo "Missing gdrive cloud protocol. Inserting..."
    # Substitute
    sed -i '/CLOUD_PROTOCOLS/s/"abfs"/"abfs", "gdrive"/' $kedro_io
    echo "Done"
else
    echo "Cloud protocol gdrive already inserted. Skiping!"
fi
```

But if was possible go back and use the `infer_storage_options` from `fsspec`could help accelerate the development of  new protocols. Because this protocols just need to be added in `fsspec` project (through MR) avoiding the second MR and approval to kedro project to accept new protocols.

Answering you question today we are working with [Google Drive API Protocol](https://developers.google.com/drive) we have expertise to work with this API but we are not using fsspec, but we see tat our implementation can be more powerful with `fsspec` abstractions and kedro framework. 

Our idea is then refactor and improve the [gdrivefs](https://github.com/fsspec/gdrivefs) from `fsspec`and ask a merge request in the `fsspec` as soon as possible. 
Some features that we have added:
 - Re-implement and make all tests work propertly
 - Better implementation of cache to store file system structure
 - Flexibility to choose google service to access google drive data
 - Upload and download of big files using chunks
 - Work with `shared drives` common to enterprise google drive accounts
 - Refactoring read/write permissions to avoid unwanted deletions 
 - Change the behavior of write to not duplicate files
 - Sent files to trash  instead  delete files permanently

**Comment by AntonyMilneQB** [comment]
Hey @Felipeasg, thanks very much for the explanation! This all makes sense. Indeed, you understood right that we previously used fsspec `infer_storage_options` but it didn't work right, so we wrote our own slightly different version in kedro. Definitely the correct path forward is for us to see whether we can go back to using fsspec `infer_storage_options`. That way you would only need to do a merge request to fsspec and not kedro in order to improve their gdrive handling. Ideally we try to delegate as much of the file-system handling to fsspec as possible rather than duplicating and writing custom things in kedro.

We've got this as a high priority task so I think we should get round to it in the next couple of weeks 🙂

**Comment by Felipeasg** [comment]
Thanks by the feedback. We are testing our implementation and I thinking that as soon as possible we will ask a MR to fsspec. Will be least tricky to us if gdrivefs work with kedro from fsspec, and I to others developers too.

Thanks.

**Comment by AntonyMilneQB** [comment]
Hi @Felipeasg, just to let you know that we have merged a PR on fsspec that adds `gdrive` to the list of cloud protocols: https://github.com/fsspec/filesystem_spec/pull/988

Once that it released, we will merge a PR on our side (https://github.com/kedro-org/kedro/pull/1714) to go back to using fsspec's `infer_storage_options` rather than our own function.

So, after fsspec and kedro have done new releases then you will no longer need manually modify `CLOUD_PROTOCOLS`. Any future changes to filepath processing should then be handled by fsspec.

Thank you for raising this issue!

**Comment by AntonyMilneQB** [comment]
The change we made to fsspec got released but then very quickly reverted since apparently it broke other things. It seems complicated to fix on the fsspec side without altering several other packages: https://github.com/fsspec/filesystem_spec/issues/1002

Hence for now at least we're going to have to maintain the list of `CLOUD_PROTOCOLS` on our side. We've added gdrive in https://github.com/kedro-org/kedro/pull/1708, which I hope works for you @Felipeasg. I'm not quite sure why changing our version of `infer_storage_options` seems to work ok but changing fsspec's breaks other things, but fixing this on the fsspec side (which is in principle what should happen) seems to be difficult to coordinate.
