### ISSUE TITLE
Replace `setup.py` workflow

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1724]
Also note that [setup.py is deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) and we will have to move away from it in general

_Originally posted by @datajoely in https://github.com/kedro-org/kedro/issues/1607#issuecomment-1168670649_

The `setup.py` workflow is deprecated and we should move towards another way of packaging in Kedro. Ideally we would move to a `pyproject.toml` driven workflow as described here: https://packaging.python.org/en/latest/tutorials/packaging-projects/, but until that's the official way of doing things we should probably use `setup.cfg` file: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html

**Comment by MerelTheisenQB** [comment]
Check what Alloy team is doing for packaging, would be good to align with them.

**Comment by deepyaman** [comment]
> Also note that [setup.py is deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) and we will have to move away from it in general

As mentioned in the second paragraph of the TL;DR, direct invocation of `setup.py` is deprecated, not the use of `setup.py` itself. It should be a relatively small change to [properly specify the build system](https://setuptools.pypa.io/en/latest/build_meta.html). Moving to `setup.cfg`-/`pyproject.toml`-based workflows do have their own advantages, but we can separate this until the `pyproject.toml` approach is out of beta and/or we know whether to move down the `setup.cfg` or `pyproject.toml` route, in order to minimize documentation (and other user-facing) changes.

**Comment by datajoely** [comment]
The argument for adopting `setup.cfg` is that it makes the eventual migration much simpler. So it's just a question of when you front load your development effort  - One huge ticket or two smaller ones.

**Comment by merelcht** [comment]
Closing in favour of https://github.com/kedro-org/kedro/issues/2152
