### ISSUE TITLE
default logging configuration doesn't log other packages than kedro

### ISSUE THREAD

**Issue by Debbby57** [kedro-org/kedro#1732]
## Description
since the 0.18.2 release, I lost the logs for the other packages than kedro in my projects, if I don't specify them in the logging.yaml
I tested with multiple packages like custom kedro plugins like kedro-mlflow (@Galileo-Galilei) and other packages like paramiko. 
If I want to have logs for thoses packages I need to update logging.yml

```yaml
loggers:
    kedro:
        level: INFO
    <my_package>:
        level: INFO
    kedro-mlflow:
        level: INFO
    paramiko:
        level: INFO
```
I think it's a bug because for me  it's difficult to ask users to add all their packages in the logging.yaml. I think the default behavior we want is to have all logs by default and use logging.yaml to remove logs we don't want.

## Context
I need all my logs by default to control the correct behavior of my projects. And if I don't want some of them I remove them

## Steps to Reproduce
1. install kedro 0.18.2
2. install kedro plugin like kedro-mlflow or another package like paramiko
3. run your project. You will see that you don't have kedro-mlflow logs or paramiko's logs
4. update your logging.yaml like above and run your project. You will have logs

## Expected Result
By default, we should have all logs.

## Actual Result
We just have kedro logs.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.2
* Python version used (`python -V`): 3.9.13
* Operating system and version: linux

Thank you for your help :)

**Comment by Galileo-Galilei** [comment]
This is a quite annoying issue I am facing too : [All tests of this PR](https://github.com/Galileo-Galilei/kedro-mlflow/runs/7508041379?check_suite_focus=true) on ``kedro-mlflow`` were working before the release and are failing since ``kedro==0.18.2``. The logs shows that the test fail because ``kedro-mlflow`` logging is no longer displayed in the console. 

The fix in ``logging.yml`` works, but like @Debbby57 I don't feel it is the right default behaviour (and it is a breaking change comapred to ``0.18.1``, so I think this is not intentional).

**Comment by Debbby57** [comment]
thank you for your reply. 
I need to think about this but for now : 
* I still don't like option 1, because as a user I don't want to search and list packages for which I want infos logs. I could be very time-consuming.
* short term, I'm going to use option 2
* I don't like option 3 but I'm just a user of kedro-plugins so I think my opinion is really facultative ;)
* Option 4 seems to be unreachable for packages which are not kedro-plugins
* I agree that option 5 is not a good option.  
* I understand why you don't want the option 6.

**Comment by AntonyMilneQB** [comment]
Just to clarify, _if_ option 4 works then it should be possible for all packages, not just kedro-plugins. Indeed I think that any packages that work outside kedro and wish to emit `INFO` level log messages must already be doing something like this, otherwise their log messages would not appear when combined with any other tool (since it would be filtered out by the Python default `WARNING` level).

Let me check this actually, since the more I think about it the more this feels like it would be the right approach, and if kedro doesn't currently work with external packages like this then it's a problem.

@Debbby57 just to understand a bit better, please can you explain exactly what are the packages for which you want `INFO` logs and why? I think it's probably not very common to have a long list of these. Given that the Python default level is `WARNING`, most Python packages expect you to just leave unaltered and don't expect users would want to see the `INFO` level messages at all.

**Comment by AntonyMilneQB** [comment]
I've just done some testing of this and believe that option 4 should indeed work. i.e. if you have a package that uses a logger set to level `INFO` log messages then those messages will still be shown during `kedro run` without any changes to logging configuration required.

This seems like the correct solution because each package then has responsibility to choose the appropriate log level for itself, and such packages will work as expected both inside and outside kedro.

In practice, what does this mean?

### For package authors (package could be kedro plugin, e.g. `kedro-mlflow`, or a general one, e.g. `paramiko`)
If you want the level of logging to be different from the Python default of `WARNING` then you should should set it as such in your package or expect users to manually set the level for your package by editing their logging.yml.

To set the logging level to `INFO` in your package, you would do `logger.setLevel(logging.INFO)`. Note that due to logging propagation, you don't need to set this separately for every single module that does `logger.info`. You can just set, e.g. `logger.getLogger("kedro-mlflow").setLevel(logging.INFO)` and it will work for any loggers below that in the hierarchy (e.g. `kedro-mlflow.something.blah.module`).

### For kedro users
If you wish to change the logging level of packages from the ones set by the packages themselves then you need to edit your logging.yml to do so according to option 1 or 2 above.

### Overall
What I've written here is actually how I'd always envisaged this working but I don't think I'd written it out explicitly anywhere, so it's good to have written down now. IMO this means the current kedro behaviour is the correct one, since it places responsibility for altering logging levels in the hands of the package authors and users. All that kedro should be responsible for is setting the logging level for `kedro` and your project package.

Let me know if this works for you. @Galileo-Galilei hopefully just setting the log level in mlflow will fix your unit tests.

**Comment by AntonyMilneQB** [comment]
I'm going to close this issue because I think there's nothing that needs to change on the Kedro side, but please do tag me in a comment and say if you disagree and I'll be happy to reopen!

**Comment by Galileo-Galilei** [comment]
Hi @AntonyMilneQB, thank you for the reply. What you say makes sense, but it would be nice if kedro plugins were set to "the same logging level" as kedro (e.g. INFO by default), but there are a few edge cases to deal with (e.g. if a user specifically specifies two different logging level in the ``logging.yml``, it should have thre priority). 

Hardcoding the package info level is not user friendly, but I guess I can use ``after_context_created`` hook to fetch the ``logging.yml`` and eventually change the default if nothing is provided for kedro-mlflow. This seems a but overkill, but easy to implement and consistent with the rest of kedro.

**Comment by AntonyMilneQB** [comment]
HI @Galileo-Galilei, it would indeed make sense to set kedro plugins to the same logging level as kedro (so `INFO` by default_

**Comment by Galileo-Galilei** [comment]
> AFAIK there's no way to do some wildcard match like kedro-*

I don't know either, but since they are loaded through an entrypoint, there is likely a way to get the names of plugins dynamically (e.g. "any package with given entrypoints"). It does not seems trivial, and likely not a high priority.

> Alternatively we could encourage plugins to log to kedro.plugins.plugin_name, so it would be kedro.plugins.mlflow for example or even just kedro.mlflow rather than kedro-mlflow

I really like the idea, but does it require having ``kedro_plugins`` installed or logging will just inherit from ``kedro`` logger, no matter if it is not an actual package?

> What is wrong with setting logger.getLogger("kedro-mlflow").setLevel(logging.INFO) within kedro-mlflow? 

Not sure I am not very familiar with ``logging`` but: 
-  what will happen if the user set a non default level in its ``logging.yml``? Will it take priority or not (this is desirable) ?
```yaml
# logging.yml
loggers:
  kedro_mlflow:
    level: WARNING # <- anything other than INFO?
```
- where do you think I should set this logging level definition ? In the package root ``__init__.py`` so it is triggered at import time?

**Comment by Galileo-Galilei** [comment]
Thank you very much for taking time to test it! 
I am completely fine woth the solution, and I think the current logging behaviour is indeed the correct one. We can likely close the issue.

**Comment by AntonyMilneQB** [comment]
Perfect, thank you for confirming! I think we're all good here then and I will close the issue.
