### ISSUE TITLE
Add parameters to `%reload_kedro` line magic 

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro#1748]
## Description

Currently you cannot pass things like `env` or `extra_params` via the line magic, but you can by importing the function.

https://github.com/kedro-org/kedro/blob/5ae97cfb70e5b0d4490132847977d482f13c840f/kedro/extras/extensions/ipython.py#L38

Why don't we introduce feature parity here?

**Comment by AntonyMilneQB** [comment]
Thanks for raising this @datajoely. It's something I've wanted to do for ages. I'm very keen for this to happen, it's certainly feasible but it's not completely trivial to implement, which is why I didn't just do it already. See these for tips on how to it: https://ipython.readthedocs.io/en/stable/config/custommagics.html
https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.magic_arguments.html

Note we get some nice extra benefits out of this like `%reload_kedro?` would show docs. Ideally no one needs to import `reload_kedro` and use it as a function any more as they currently do.

Note we should make sure that `%reload_kedro <project_root>` still works without explicitly needing to specify an argument name for the project path. `%reload_kedro` with no arguments should also still work as it does now.

It's also worth noting that at some point we _might_ want to change the way we handle `project_path` from being a `global` variable to instead making a stateful `%reload_kedro` as a class. It's not essential, but anything we do here to add arguments would ideally be compatible with that approach too.
