### ISSUE TITLE
Should `kedro test` and `kedro lint` be deprecated?

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1766]
Investigate what the alternatives would be for users currently using `kedro test` and `kedro lint`. 
Write up a plan to deprecating `kedro lint` and `kedro test` (including how the users can "migrate" to these alternatives) or alternatively summarise why those commands shouldn't be deprecated.

Also keep in mind that the alternatives should still make it possible to have a linted/testable Kedro template.

**Comment by MerelTheisenQB** [comment]
The original research done on this topic: https://github.com/kedro-org/kedro/issues/1293

**Comment by jmholzer** [comment]
<h2>Proposal</h2>

The CLI commands `kedro test` and `kedro lint` should be deprecated because this is the consensus in #1293.

<p />

A summary of the key arguments for deprecation:

1. Utilisation by users is very low.
2. The interface for Kedro would become simpler.
3. Management of dependencies would become simpler.
4. There would be less code to maintain.
5. It is consistent with other design choices (e.g. the move to `kedro-datasets`, the deprecation of `kedro install`).

A summary of the key arguments against deprecation:
1. Some users do use these commands.
2. Any of the discussed alternatives are likely to result in even lower utilisation.
3. These commands are congruent with the Kedro design philosophy.

My view is also that the commands should be deprecated. Both commands are wrappers for tools with many alternatives. I believe that if a user knows the value of testing and linting code, they either:

1. Know how to set up and use the wrapped tools autonomously.
2. Have a preference for alternative tools that are not wrapped by these commands.

In these cases, the commands offer limited to no utility.

<h2>Plan</h2>
To mitigate the disadvantages discussed in the arguments against deprecation:
<p />

1. Add demos for implementing testing and linting in a Kedro project to the documentation.
2. Add code (e.g. a decorator) for both commands to generate a warning to the user that they will be deprecated. A link should be included to the documentation from step one.
3. Consider the creation of a plugin that offers `lint`, `test` and other deprecated commands.

In https://github.com/kedro-org/kedro/issues/1293, step three of this plan is somewhat controversial, since it represents an up-front and ongoing investment. One option is to create this plugin as a community-led project. In any case, further discussion is warranted for this step.

**Comment by MerelTheisenQB** [comment]
This summary makes sense to me, but I'm missing what the concrete the alternatives would be for users currently using `kedro test` and `kedro lint` and how the users can "migrate" to these alternatives.

**Comment by deepyaman** [comment]
> My view is also that the commands should be deprecated. Both commands are wrappers for tools with many alternatives. I believe that if a user knows the value of testing and linting code, they either:
> 
> 1. Know how to set up and use the wrapped tools autonomously.
> 2. Have a preference for alternative tools that are not wrapped by these commands.
> 
> In these cases, the commands offer limited to no utility.

This is a fair view. However, why should we even "add demos for implementing testing and linting in a Kedro project to the documentation" in that case? I'd rather a user who "knows the value of testing and linting code" choose their own tools and read the respective docs, so there's nothing for us to maintain here. Otherwise, Kedro maintainers will spend time resolving issues setting up `pytest` and `flake8` when we in fact have no strong view there. IIRC @AntonyMilneQB mentioned something in this vein (I could be wrong). I think it could be handled with a docs page stating the linter config Kedro uses (i.e. project template is linted with isort, black, flake8).

On that note, I think the plan is missing the bit on how to make sure the project template is still linted (somehow).

**Comment by yetudada** [comment]
This write-up and evaluation is stellar 🎉 An additional benefit is a simpler starter for new users. 

If I quickly scan the documentation and starters it would mean that we would be making the following changes (if I haven't forgotten anything):

 - Starters:
   - Remove `setup.cfg`
   - Edit `pyproject.toml`
   - Edit `src/requirements.txt`
 - Documentation:
   - Edits to anywhere where `setup.cfg` is mentioned like in the [Project directory structure](https://kedro.readthedocs.io/en/stable/get_started/example_project.html#project-directory-structure), the section on [Astronomer](https://kedro.readthedocs.io/en/stable/deployment/airflow_astronomer.html?highlight=setup.cfg), and the one on [Starters](https://kedro.readthedocs.io/en/stable/extend_kedro/create_kedro_starters.html?highlight=setup.cfg)
   - Add new sections on testing and linting, probably under **Development** or **Tools integration**
   
I like the documentation addition because in future, the section on testing could be expanded to cover #1271. I think @deepyaman's comment is the only thing left to cover, which is how do we make sure that we deliver linted and tested starters to our users without those configuration files being present in the starters.

**Comment by yetudada** [comment]
While I was walking, I realised there are more changes 😂 What should happen to `src/tests`?

**Comment by MerelTheisenQB** [comment]
Can't we just keep the linting and testing setup in the starters as is now and use that as an example for users to show how they can configure their project to have linting and testing? I realise that with this approach we don't clean up as much, but I feel this would solve the problem of how we keep the starters in good shape and have concrete examples for users how to set up linting and testing. The only change is that we don't lint and test by doing `kedro lint` and `kedro test` but by running the underlying commands.

**Comment by jmholzer** [comment]
In technical design (14/09/22) we decided on the following action items:
1. Short guides for linting and testing should be written and added to the docs. Depending on the traffic metrics for this part of the docs, a next step of creating either a lint / test starter* (see below) or a plugin will be considered.
2. Explore whether the /tests folder **and / or** the linting configuration (requirements, config files) should be kept or dropped in the starters **and / or** template.

* @yetudada proposed moving the elements needed to add both commands to a starter project. This may provide significant advantages in ease of maintenance relative to the plugin option.

**Comment by jmholzer** [comment]
In technical design (14/09/22) it was concluded that both commands should be deprecated. The following action items were agreed:

1 (#1619 and #1620). Short guides for linting and testing should be written and added to the docs. Depending on the traffic metrics for this part of the docs, a next step of creating either a lint / test starter* (see below) or a plugin will be considered.
2 (#1849). Explore whether the /tests folder and / or the linting configuration (requirements, config files) should be kept or dropped in the starters and / or template.

\* @yetudada proposed moving the elements needed to add both commands to a starter project. This may provide significant advantages in ease of maintenance relative to the plugin option.
