### ISSUE TITLE
Create nodes in a loop with text input 

### ISSUE THREAD

**Issue by fesaaved** [kedro-org/kedro#1784]
I know that It is possible to add text inputs to nodes with the lambda function as is described in #213.
However, if I create nodes in a loop with a lambda function iterating text input, lambda functions will only take as input the last text input at the time of execution, for example:

`for var in ['t1','t2','t3']: 
    list.append(node(func: lambda x: function_0(x,text_input=var), 
    inputs=...)`

When I run the code the 3 nodes will receive as input 't3', this is part of lambda function properties and is not an issue. 

I would like to define generic nodes that I would like to use only changing a text input. I have the feeling that this is not a very kedro-like solution, however, creating three different variables in the catalog [t1,t2,t3], I think it doesn't make sense and if this could be implemented in kedro will add a lot of flexibility to create nodes.

**Comment by AntonyMilneQB** [comment]
This is actually not such a weird thing to do, and it's already possible using [modular pipelines](https://kedro.readthedocs.io/en/stable/nodes_and_pipelines/modular_pipelines.html). It's not super intuitive or obvious how you use this solve to your case but it's not hard to implement. The strategy is:
* define literal string inputs using parameters, e.g. `params:input`
* define a `template_node` that isn't actually used anywhere but will be transformed to different namespaces. This means that catalog inputs/outputs called `abc` will be transformed to `namespace.abc`
* form a `pipeline` out of this `template_node` and transform it to each namespace required
* define parameters that match these required namespaces, so `params:t1.input` etc.

Here's the code for it:

```
template_node = node(func=lambda x: x, inputs="params:input", outputs="x")
all_nodes = sum(pipeline([template_node], namespace=var) for var in ["t1", "t2", "t3"])
```

and in your parameters.yml file:
```
t1.input: t1
t2.input: t2
t3.input: t3
```

I see there are ways around this limitation of lambda functions which might also help your particular case - see https://stackoverflow.com/questions/19837486/lambda-in-a-loop. People tend to pass literal arguments by using `partial` rather than `lambda` in kedro, which I think would avoid your problem in the first place.

The advantage of the modular pipeline approach is that it's much more generic and will allow you transform whole pipelines (not just nodes) in a more systematic way that ensures node names don't clash, etc.

**Comment by MerelTheisenQB** [comment]
Hi @fesaaved, do you need more support on this issue or are you okay with closing it?

**Comment by fesaaved** [comment]
Hey @AntonyMilneQB, 
I switched to modular pipelines as you suggested and it works perfectly now. I had to update the Kedro version for this purpose, but it worth it. Thank you very much for the response!

**Comment by MerelTheisenQB** [comment]
Thanks for responding @fesaaved, I'm very glad to hear your problem was resolved! 😄
