### ISSUE TITLE
Consider whether `find_pipelines` should handle a simplified project structure

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro#1812]
Following a conversation in https://github.com/kedro-org/kedro/pull/1706. Just creating the issue while I remember. I'll write more details when I get the chance.

1. Should we support the "simplified" project structure? I think probably yes. If no, we should change the starters that use this.
2. If yes, should `find_pipelines` support this simplified project structure? I think probably yes. 
3. Should `find_pipelines` support both the simplified and extended project structure in a single project? Probably not very important either way.

**Comment by noklam** [comment]
Dropping my view here:
 * I think it should be default for all starters, so users don't have to discover the `find_pipelines` feature, including `kedro new` with the default project template.
 * I think it should support the simplified case, simply because a unified workflow would be much nicer.

I could be biased because I almost always use `kedro new -s pandas-iris` and delete the unnecessary bit, because `spaceflights` has too much things to delete and the empty `template` has too little thing, I have to find all the right `import` which I end up just searching the `pandas-iris` template anyway.

**Comment by deepyaman** [comment]
> 3\. Should `find_pipelines` support both the simplified and extended project structure in a single project? Probably not very important either way.

If there is a `src/<package_name>/pipeline.py` file that exposes `create_pipeline()`, it can't be a named pipeline, so I was going to initialize `__default__` to that pipeline, rather than an empty pipeline (i.e. essentially in https://github.com/deepyaman/kedro/blob/1c1883ac1c595929171a8b2af666b7fe7d514a16/kedro/framework/project/__init__.py#L280).

Then, if somebody creates new modular pipelines with `create_pipeline()` methods, the login in `register_pipelines()` would add them on top of the `pipeline.py` default. How does that sound?

**Comment by AntonyMilneQB** [comment]
Yeah, I like it 👍 The important thing is that `pipeline_registry.py` file should look exactly the same in both the simplified project and the multi-pipeline project cases. So long as that holds, I'm not too worried about whether/how we support the "`pipeline.py` + `pipelines` folder in one project" case. But this way definitely makes sense and I think is in keeping with what @noklam suggested on the PR.

One thing we should probably do (not necessarily now) is describe somewhere what these two acceptable project structures are. The simplified view is what we use in https://kedro.readthedocs.io/en/stable/get_started/example_project.html (since it's based on `pandas-iris`).

**Comment by noklam** [comment]
> > 3\. Should `find_pipelines` support both the simplified and extended project structure in a single project? Probably not very important either way.
> 
> If there is a `src/<package_name>/pipeline.py` file that exposes `create_pipeline()`, it can't be a named pipeline, so I was going to initialize `__default__` to that pipeline, rather than an empty pipeline (i.e. essentially in https://github.com/deepyaman/kedro/blob/1c1883ac1c595929171a8b2af666b7fe7d514a16/kedro/framework/project/__init__.py#L280).
> 
> Then, if somebody creates new modular pipelines with `create_pipeline()` methods, the login in `register_pipelines()` would add them on top of the `pipeline.py` default. How does that sound?

This sounds very reasonable 👍🏼
