### ISSUE TITLE
Replace Pipeline with pipeline across all tests

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro#1833]
## Description
Currently, `Pipeline` is used to instantiate objects of this class across the testing code base. This should be updated to use the `pipeline` factory in `kedro.pipeline.modular_pipeline`.

## Context
This comes from @AntonyMilneQB's comment on #1795 suggesting that these changes be made for the test files modified for that feature.

**Comment by ziyad00** [comment]
This is my first issue and I'd like to be assign

**Comment by jmholzer** [comment]
Excellent! So happy to have you onboard @ziyad00

**Comment by adamfrly** [comment]
Is this issue still open? I'd be happy to pick up the work for it

**Comment by AntonyMilneQB** [comment]
I believe it is indeed still open. @jmholzer?

**Comment by jmholzer** [comment]
Hey @adamfrly, yes this issue is still open 🙂 Awesome! Would be glad to have your contribution.

**Comment by AntonyMilneQB** [comment]
From what I recall I think all the remaining instances of `Pipeline` cannot be fixed just by find and replace (all the ones that could have already been) since there would be a clash of variable name and function name `pipeline`. Hence there would be a need to rename some variables here, not just do a naive find and replace. Does that sound right @jmholzer?

**Comment by jmholzer** [comment]
@AntonyMilneQB yes! This is exactly right 🙂. As soon as we import `pipeline` there will be a good deal of shadow naming going on in many of the files, so variable names will have to be changed.

**Comment by adamfrly** [comment]
Sounds great! I was thinking of something along the lines of `from kedro.pipeline.modular_pipeline import pipeline as modular_pipeline` to avoid the clash
