### ISSUE TITLE
Should testing and linting dependencies and configuration be dropped from starters and / or templates?

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro#1849]
## Introduction

In #1766, it was decided to deprecate the commands `kedro test` and `kedro lint`.

It should now be decided whether to keep the folder structure, dependencies and configuration files (referred to from here on as the 'items') that these commands rely upon in Kedro's project starters and project template.

## Background

As a starting point for this exploration, the key arguments for / against removing the items are summarised.

The key advantages to removing them are:
1. A simpler folder structure, which @yetudada identified as being a key issue for new users.
2. Fewer dependencies to manage.

The key disadvantages to removing them are:
1. Testing and linting the template and starters currently uses the items, removing them will mean finding an alternative.
2. These items (e.g. the src/tests folder and linting dependencies) are viewed as a nudge to the user, reminding them of the importance of testing and linting.

## Outcome

The outcome of this ticket should be an actionable plan describing which of the items to keep and which to remove in:
1. The project template
2. The starter projects

An alternative means of testing / linting the starters and template is a key outcome of this issue in the case that the items should be removed.

**Comment by MerelTheisenQB** [comment]
`test`
Testing requires a lot less setup, so in my opinion it's fine to remove the setup and dependencies for it from both the template and starters. 

`lint`
I've checked how we ensure the template and starters are linted currently and found the following:
- The template is not linted at the moment. `pre-commit` skips the template because of the cookiecutter `{{ ... }}` format in several files. In the e2e tests we run `kedro lint` on a test starter, which is not the actual template. 
- When you run `kedro lint` on a new project it will actually reformat some things.
- Starters are linted in the e2e tests, and so we can just replace the `kedro lint` call with the underlying calls to black, flake8 and isort. 
   - To make these checks all pass we would need to add test setup for flake8, because the default max line length is 79 and we've always worked with a max lint length of 88.

Considering the template isn't actually linted currently, I'd suggest to remove all lint setup from that.
I'd still be in favour of having one starter (probably spaceflights) with full linting config in it so we can point to it as an example for users how to configure their linting.

**Comment by MerelTheisenQB** [comment]
Closing in favour of the follow up tickets:

- [ ] https://github.com/kedro-org/kedro/issues/1947
- [ ] https://github.com/kedro-org/kedro-starters/issues/106
- [ ] https://github.com/kedro-org/kedro/issues/1948

**Comment by MerelTheisenQB** [comment]
Closing in favour of the follow up tickets:

- [ ] https://github.com/kedro-org/kedro/issues/1947
- [ ] https://github.com/kedro-org/kedro-starters/issues/106
- [ ] https://github.com/kedro-org/kedro/issues/1948
