### ISSUE TITLE
Enable async loading of datasets by default

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro#2036]
## Description
> Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

In large projects or situations where a node has many inputs users may be frustrated by the current behaviour where large datasets (especially in non-lazy contexts) are loaded sequentially and this can make the process quicker. We have the `async` runner flag, but even as an experienced user it's easy to forget this exists independently of the runner choice. 

Does it make sense to make this the default behaviour?

## Context
> Why is this change important to you? How would you use it? How can it benefit other users?

I guess the reason we wouldn't want to do this is related to the general pain of parallelism in Python. I suspect it wouldn't work with Spark for example. Potentially we could do an order of precedence where we try async and fall back to sync if there is an issue?

**Comment by idanov** [comment]
This will make some datasets fail by default when used, i.e. the Spark datasets, so I would recommend we don't change the current behaviour. It's better to have a working default option, than an occasionally failing one and people should turn this on only if they need/want it.

**Comment by datajoely** [comment]
What are your thoughts on some sort of heuristic which provides a warning / suggestion to consider this?

**Comment by merelcht** [comment]
@datajoely Do you mean adding some logging that would remind people of the functionality? Would improving the docs maybe me a good low effort solution?

**Comment by datajoely** [comment]
it was an ambitious ask, but we could in theory look at all of the datasets in a catalog that have the `_SINGLE_PROCESS` thingy and then recommend the `--async` option for performance

**Comment by merelcht** [comment]
We discussed this issue in **Technical Design** on 8/3. 

The opinions on enabling async loading of datasets were mixed, some people we're in favour of making it the default, others thought it would be better to provide the suggestion to use `--async` depending on the data used. Because there's more to be done to improve the Runners the following actions will be taken:
- [ ] Add more description to the "Runner" milestone: https://github.com/kedro-org/kedro/milestone/28
- [ ] Update the default logging so it says "Async is disabled. You can enable it by ..." instead of it only mentioning it's enabled when a user specifies `--async` (https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously)
- [ ] Create a blog post to showcase ways of improving run performance.  

**More details on the discussion:**
The discussion revealed more issues and also ideas to improve performance of Kedro runs. Some points made:
- It's not entirely clear why the Spark datasets don't work with `--async` or with e.g. the `ParallelRunner`. It would be worth looking more closely at how we can make the Spark datasets better.
- We don't actually know how much the speed up of using `--async` is, so a good exercise would be to manually test what the performance gain is from using `--async` for each dataset. Could create a toy project that uses all datasets.
- Do we actually know why people aren't using `--async`? 
   - It might well be that awareness about the feature is an issue. 
   - Or perhaps people simply don't care about performance. 
- People could also use `CachedDataSet` to improve performance, but that dataset isn't working perfectly and needs some love.
- Ideally we would have a smart runner that depending on your data and use case will "decide" which way of running your pipeline is the best. This is of course very complicated, but would likely improve the performance experience.
- Kedro already offers multiple features that help with improving run performance, but people seem not to know about them or how to use them.
