### ISSUE TITLE
Versioned PartitionedDataSet

### ISSUE THREAD

**Issue by mle-els** [kedro-org/kedro#2043]
## Description

Is it possible to add a new class that handle versions of a PartitionedDataSet? So, when we replace `PartitionedDataSet` with `VersionedPartitionedDataSet` things should work the same way except that multiple folders are stored.

## Context

There are two reasons for this feature:
1. Spark datasets can be versioned and to read those into Pandas using transcoding, we'll need a versioned PartitionedDataSet.
2. I'd like to compare changes in the output of my pipeline (and store past output for future reference) which cannot be stored in any other format than a PartitionedDataSet. Others might have the same need.

## Possible Implementation
Borrow code from other versioned datasets.

**Comment by merelcht** [comment]
Thanks for raising this @mle-els ! We've had similar requests before. The main reason we haven't implemented this functionality yet, is because it's very complex. We have now decided to investigate both the demand from users and implementation of a versioned partitioned dataset. This work will be tracked in https://github.com/kedro-org/kedro/issues/2115

**Comment by merelcht** [comment]
Closing this issue in favour of: https://github.com/kedro-org/kedro/issues/2115
