### ISSUE TITLE
Curate technical FAQs that usually come through Slack/Discord

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2070]
## Description

Subtask for https://github.com/kedro-org/kedro/issues/1985 

- Curate list of questions that are asked a lot on Slack/Discord and should go on the FAQs page in the docs
- Write good answers for the questions

**Comment by stichbury** [comment]
I'm not too keen on this solution as I've articulated in a previous issue. I don't think we should have FAQs in the docs because they date and it's hard to keep them general enough to be relevant while specific enough to solve any individual problem.

I instead think we should have a better way for people to search the archive of previous Q&A pairs to get information, and move the FAQs that we do have, that are high level, onto the website.

If we know there are specific commonly-asked questions, we should instead deal with what they are and why they are asked regularly. Maybe we need more documentation about a particular issue (or to solve that particular problem in the associated docs). Maybe we need a change in the framework or viz to avoid the issue happening. I don't think that a knowledgebase is the answer, personally.
