### ISSUE TITLE
Usability Testing for Spaceflights Tutorial

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#2091]
## What is this?
A series of usability tests that would document areas where new users of Kedro get confused or stuck when working their way through our documentation from installation to completion of the Spaceflights tutorial so that we can prioritise changes to our documentation and the Framework. 

## Why do we care about this?
This issue is linked to #2089. In addition, we marked a secondary and ongoing priority to explore easing the onboarding journey for new users of Kedro and explaining or tweaking software engineering jargon in our documentation. 

We're aware that most of the issue is the software engineering fundamentals we expect users to know before they learn Kedro, and we will address that in a different issue (#2089). This is one is limited to users' initial experience of Kedro. 

_"The tutorial is built in a way that it expects you to understand software engineering, at least the principles of it, to some certain extent. But we are talking about people here who don't even know how to create their Python environments."_

## What needs to happen?

We need to recruit people who have yet to use Kedro _and_ do not have software engineering expertise but do write code for data and ML projects. 

We would ask the users to record their walkthroughs of the documentation as they complete Spaceflights and then make notes of where users get stuck or confused. Users would be expected to describe their workflow as they go through it. 

We should get a map of users' mental states and an understanding of where our users are getting stuck. It will enable us to prioritise interventions in our documentation and product.

**Comment by stichbury** [comment]
@yetudada I put together a chart that shows the conversion funnel across the pages in the tutorial in Heap: https://heapanalytics.com/app/env/537308175/funnel/chart/Conversion-funnel-for-spaceflights-tutorial-3375559

This is for the existing content rather than the new pages in 18.4 but what I'm hoping to achieve is to increase the "conversion" and see a greater number of completions. Sure, the tutorial was always optional towards the end, but I don't think we made that explicit. By making the tutorial shorter and shifting viz out of the bundle, I think it'll be less intimidating and therefore more people will stick with it.

**Comment by astrojuanlu** [comment]
Suggesting we do this after #2261.
