### ISSUE TITLE
Text shown within tables in Kedro docs is very small

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2143]
## Description
As the title describes. Take a look at https://kedro.readthedocs.io/en/stable/get_started/new_project.html for an example:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/5180475/208684242-84535519-e809-4719-bc71-43ce0a8c72c9.png">

I'm on Chrome, most recent version, MacOS

## Context
It is likely that we'll move away from RTD hosting so it's not worth worrying if there's a chunk of work resulting from having to use the CSS from RTD. But it may be a straightforward enough fix, and even if it won't be something we can resolve for readers until the next Kedro release, it would probably be worth fixing if it's a small task.

cc-ing @tynandebold for insight

**Comment by tynandebold** [comment]
Looks like the theme style we're using for the page is setting a unit of `1rem` on the paragraph tags (`<p>`) within the table.

A unit of `1rem` uses whatever size is set on the root element of the webpage. In our case, that's `11.2px`, which is why the table text is so small.

The fix is to change the unit from `1rem` to `1em` for both the `font-size` and `line-height` style properties. That will have an output that looks like this:

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/16869061/208704927-c9f283ae-9601-4c86-aca5-41dcabef50c7.png">

I'm not sure how to update the style of the RTD pages. Wouldn't think this would be too hard though.

**Comment by stichbury** [comment]
Thanks @tynandebold ! Did you make a change to the CSS in one of the docs/source files? https://github.com/kedro-org/kedro/tree/main/docs/source/css

I am wondering if that is all it takes to push a change through to RTD, or whether they always build against their own copy of the CSS. Please could you point me at the file to change and the diffs, and I'll make a PR and let's see what happens to the `latest` version of the docs if we merge it in!

**Comment by tynandebold** [comment]
I did it locally, in the browser. I've just opened a PR though, #2150. Are you able to test it out locally?

**Comment by stichbury** [comment]
@tynandebold I've just checked on the RTD site for the latest docs https://kedro.readthedocs.io/en/latest/get_started/new_project.html

Sadly, it is not picking up the fixes you put in place, and this could well be just the way it is 🤷 since RTD rebuild the docs and possibly don't pick up our CSS.

It's still worth the fix because of future plans.

**Comment by tynandebold** [comment]
Shame. Is there a way to test this locally before merging next time?

**Comment by tynandebold** [comment]
I don't think the change is actually live on the docs site yet.

My additions aren't showing up in the `theme-overrides` file: https://kedro.readthedocs.io/en/latest/_static/css/theme-overrides.css
