### ISSUE TITLE
Add an option to run a specific namespace in `KedroSession` run and `kedro run`

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#2145]
## Description

Currently there's a way to select different sections from a pipeline to run, but selecting by namespace is missing. We should add a way for users to run a specific subpipeline (namespace) by executing this in the terminal:

```
kedro run --namespace data_engineering.preprocessing
```

```
kedro run -ns data_engineering
```

This will run all nodes whose namespace starts with `data_engineering.preprocessing`, regardless of depth. In order to implement this, we'd need to provide a similar option in `KedroSession`.
The `Pipeline` object already has the relevant filter `only_nodes_with_namespace` which can be used for implementing this functionality.

## Context

This change is important to providing a nice way to convert Kedro pipelines into orchestrator pipelines. Currently most conversions of Kedro pipelines happen on a node to node mapping,
which is far from ideal. Orchestrator run pipelines tend to be much less granular than Kedro pipelines and this 1-to-1 translation produces suboptimal executions. By enabling running pipelines
by namespace, we will make it easier to create much more clever deployment plugins, which will take advantage of the topology of the underlying pipelines better.

## Possible Implementation

To be decided by the team.

## Possible Alternatives

**Comment by merelcht** [comment]
This should be `multiple=False` just like pipeline

**Comment by noklam** [comment]
Currently there's a way to select different sections from a pipeline to run, but selecting by namespace is missing. We should add a way for users to run a specific subpipeline (namespace) by executing this in the terminal:

```
kedro run --namespace data_engineering.preprocessing
```

```
kedro run -ns data_engineering
```


This will run all nodes whose namespace starts with `data_engineering.preprocessing`, regardless of depth. In order to implement this, we'd need to provide a similar option in `KedroSession`.

## Changes
* Extend `KedroSession.run` arguments
* Extend `kedro run` CLI arguments
