### ISSUE TITLE
Migrate kedro's setup.py to pyproject.toml

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#2152]
## Description

The Python community is slowly moving to pyproject.toml as a package definition format and away from big and verbose setup.py files. Our Kedro package setup is still exclusively done in setup.py, with some parts in setup.cfg and pyproject.toml. We should move entirely to a pyproject.toml Python package definition for future-proofing our package setup.

## Context

Adhering to the Python community standards is important in order to make it easier for future contributors to Kedro.

## Possible Implementation

We can do that in one go and by creating a number of requirements.txt files as needed for the extras or dev dependencies. Here's a good starting documentation on how our pyproject.toml should look like: https://setuptools.pypa.io/en/latest/userguide/quickstart.html

## Possible Alternatives

N/A

**Comment by merelcht** [comment]
We might be able to use this: https://github.com/asottile/setup-py-upgrade

**Comment by astrojuanlu** [comment]
Related: I spotted this while running `kedro package` on the spaceflights tutorial:

```
/Users/juan_cano/.micromamba/envs/kedro310/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```

We should get rid of `setup.py` everywhere.

**Comment by astrojuanlu** [comment]
Notice that this doesn't have to be done in one go: setuptools supports having `pyproject.toml` for static stuff, and `setup.py` for dynamic stuff. There are a couple of dynamic bits:

Moving all of  `dependency/requirements.txt` to `pyproject.toml` is a bit more work, because that file is used in behave:

https://github.com/kedro-org/kedro/blob/fd42a5a17523e645dce2df7488a204ff3662fb81/features/steps/cli_steps.py#L397-L403

And then `extras_require` need a bit more work as explained above.

Hence a first step towards having _mostly_ static metadata is fairly straightforward:

- Remove `test_requires` (it's deprecated)
- Replace `python setup.py` in `Makefile` by the appropriate command (`pip install build && python -m build`)
- Move everything except `install_requires` and `extras_require` from `setup.py` to `pyproject.toml` (no more need to dynamically read `README` or version file, `setuptools` takes care of it)

**Comment by astrojuanlu** [comment]
Even though gh-2475 didn't technically obliterate `setup.py`, now that most of the project metadata is in `pyproject.toml` maybe we could just keep `setup.py` around for our extras mangling and close this issue. What do others think?

**Comment by merelcht** [comment]
@astrojuanlu It looks like all extra requirements are dataset related, so those will be removed anyway when datasets are removed from Kedro core in `0.19.0`. So I'm guessing there isn't really anything we can do until then?

**Comment by astrojuanlu** [comment]
@merelcht good catch, yeah I agree!

**Comment by merelcht** [comment]
We have https://github.com/kedro-org/kedro/issues/2127 for that, so I think we can indeed close this issue as done 🙂
