### ISSUE TITLE
Create a `kedro jupyter-init` command to setup a Jupyter kernel for Kedro

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#2168]
Design a `kedro jupyter-init` command (name is up for debate) which will create a Jupyter Kernel to automatically load the Kedro extension
- Use [the jupyter client kernelspec API](https://jupyter-client.readthedocs.io/en/stable/api/kernelspec.html#jupyter_client.kernelspec.KernelSpecManager.install_kernel_spec) to do that from Python
- Make the command available only if `jupyter` is installed, else show a warning Jupyter is not installed
- Add the Kedro icon to the KernelSpec
- Use the work done here: https://github.com/kedro-org/kedro/pull/1355/files#r830876411

**Comment by AntonyMilneQB** [comment]
This should be very easy to do since all the relevant code is in `_create_kernel` so we just need to create an appropriate CLI command that wraps it.

I mentioned the idea of this to @BenjaminLevyQB a while ago and he seemed to like it. Note that it seems to be possible e.g. on databricks to create (and then select from the notebook) a Jupyter kernel even though you wouldn't execute `kedro jupyter notebook/lab` itself there, so I think having a separate command to just do the setup here makes sense.

So long as we're keeping the `kedro jupyter lab/notebook` commands let's make sure the command is part of that group, e.g. `kedro jupyter init` or `kedro jupyter setup`.

**Comment by jmholzer** [comment]
Discussed in backlog grooming 30/01/23:

1. Potentially modify name of command to e.g. `setup` or `kernel`.
2. Command to be made part of `jupyter` group, not a 'root' command.
