### ISSUE TITLE
Further enhancements to spaceflights tutorial following onboarding reviews

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2261]
There are a few extra tweaks we can make to the spaceflights tutorial following onboarding by @amandakys and @astrojuanlu and this ticket captures those. I'll expand them more fully in due course, but want to record the basics here.

From @amandakys 

* Reduce branches so the flow of the tutorial is linear for different reader types (windows vs MacOS etc)
* Reduce notes because they are distracting (or hide the details)
* Make the expandable code sections consistent (everything or nothing)
* Consider an "express tutorial" for those using the Starter, rather than the branching approach which tells the starter users not to bother copying code, repeatedly.
* Add tooltips for Kedro terminology (Sphinx extension)
* Talk about conda knowledge as part of pre-requisites
* Explain how to find out Kedro version
* Clarify what an ipython session looks like
* Remove note about adding the pipeline to the registry (unless already done?)
* Consider how to integrate viz since graphics aren't that intuitive

From @astrojuanlu 
Quite a lot to think about, but one thing I definitely need to fix immediately:

* https://kedro.readthedocs.io/en/latest/get_started/summary.html says "Following the tutorial, you’ll learn how to [visualise a Kedro project](https://kedro.readthedocs.io/en/latest/visualisation/kedro-viz_visualisation.html) and learn more about [combining Kedro with a Jupyter notebook](https://kedro.readthedocs.io/en/latest/notebooks_and_ipython/kedro_and_notebooks.html)." but the tutorial doesn't do that -- the notebook stuff is separate.

<I'll record the rest here shortly>

**Comment by astrojuanlu** [comment]
I'm working on _writing down_ further enhancements to the spaceflights tutorial, as well as various bits I'm finding about the CLI, hence I added this issue to the current sprint. However, other tasks have higher priority, and as such _implementing_ those enhancements will likely need to be done at a later stage.

**Comment by astrojuanlu** [comment]
Some notes below. My north star is the 4-quadrant framework [Diátaxis](https://diataxis.fr/).

![Image](https://user-images.githubusercontent.com/316517/216081361-e217be0c-b1fc-4a4d-b746-8f2a8abd5f88.png)

_(Disclaimer: All statements below are my opinion and can be debated)_

First of all, the website contains 2 calls to action that sound very similar: "Get started" and "Take the Tutorial". The two overlap a bit, because they both cover basic commands like `kedro new`, starters, `kedro run` and so on, but the spaceflights tutorial is of course much more comprehensive, and the "Get started" section contains lots of _explanations_ that somehow get in the way. Wondering if this landing could be simplified. The "Get started" section is not in scope for this issue though, so I'll skip to the spaceflights tutorial.

I'm going to assume that the target audience for the tutorial are

- Data scientists (hence knowledge about machine learning, statistics, lightweight coding)
- with Python experience (basic syntax, data manipulation with pandas)
- that don't know anything about Kedro but want to learn more (hence they're hopefully motivated to complete the tutorial from beginning to end)
- and are confident with the terminal of their operating system of choice (although we should narrow this down to a UNIX-like terminal like WSL2 for Windows + Bash on Linux + ZSH on macOS).

In general, I think the tutorial contains too many _explanations_ that are a bit distracting, and many optional parts that [made me think a bit too much](https://www.goodreads.com/book/show/18197267-don-t-make-me-think-revisited) and could perhaps belong to a _how-to guide_. Now, some specific things:

- The tutorial kind of assumes an IDE (rather than, say JupyterLab). We should probably make that more explicit, and point readers towards other Jupyter-friendly pages ([Kedro and Jupyter Notebooks](https://kedro.readthedocs.io/en/stable/notebooks_and_ipython/kedro_and_notebooks.html), [Kedro as a data registry](https://kedro.readthedocs.io/en/stable/notebooks_and_ipython/kedro_as_a_data_registry.html)).
- The optional `git` part suggests Gitflow, but then the Flatiron that comes right before doesn't mention it. Gitflow is a quite heavy workflow and most beginners will either pick something simple for their personal projects or adopt whatever their team is using, so I think we should be less opinionated about it. Also, many people using GUIs for git (like VS Code, Gitkraken and such) so maybe we don't even need to include a micro crash course on git.
- In any case, I think instructing readers to either (1) commit their changes at the end of every chapter or (2) doing everything from the GitHub interface (potentially using Gitpod or Codespaces for terminal access) would be a nice touch.
- There are some deprecated commands mentioned there, like `kedro lint`, `kedro build-docs` and so on. We should replace or remove those.
- The part that covers the config doesn't explain whether `credentials.yml` ends up being tracked in version control or not, we could clarify that a bit.
- "Ask the community for help" and the FAQ shouldn't be part of the tutorial, but top-level pages.
- "Bruce Philp and Guilherme Braccialli are the brains behind a layered data-engineering convention" but then Joel's blog post on Medium never mentions them.
- Some of the commands include absolute paths. We should either reduce those to a minimum (since they assume a given operating system).
- Some types are not well specified, for example `name: str = None` should be `name: str | None = None` or `name: Optional[str] = None`.
- Initially I found it surprising that the default behavior is to _not_ write the datasets to disk (until they're manually registered). Makes the default behavior resemble a "dry run", since there is no output. This is not a criticism of the tutorial itself, just an observation.
- The first time the `__default__` pipeline is mentioned, it's not explained - I only understood it at the very end. If we don't want to explain it at that point, we could as well remove it.
- The "modular pipelines" chapter introduces `kedro viz` for the first time. We could be more purposeful about it.
- I proposed obliterating `.egg` files from Kedro at #2273.
- The tutorial could end with a "where to go next" that points users towards other useful parts of the documentation.

**Comment by stichbury** [comment]
Just to note that #2273 is now purely about any changes to the framework to stop producing eggs. This ticket will take care of any associated docs changes.

**Comment by astrojuanlu** [comment]
One more: the default project name for the `spaceflights` starter is `Spaceflights`, and this might cause confusion (see https://github.com/kedro-org/kedro/pull/2364).

**Comment by stichbury** [comment]
This comment records work done, work in progress and work to do.

## Work done

* Reordered pages to keep hands-on separate from concepts 
* Renamed sections of docs to make the on-boarding more linear
* Removed summary page in the get started section and added those sections where appropriate
* Revised the copy in the page about getting started to push the iris example out of the limelight
* Removed the section about Git
* Removed the option to copy/paste code — this is now an express tutorial without any actions required from the reader (except thought)



## Work to do

* Review all the notes and work out if they're all needed. Likewise all the explanatory text that may "get in the way"
* Make the workflow more explicit (we assume the reader isn't using a notebook, so should say so)
* Remove deprecated commands like Kedro lint, Kedro build-reqs 
* No longer any need to add the pipeline to the registry
* Clarify whether credentials.yml is tracked in version control
* Introduce Viz earlier in the tutorial as it's a key part of the product
* Check all the file paths
* Add expandable sections around every code snippet
* Is there a suitable "What you've learned" and "where to go next?" section?
* Renaming throughout from "Kedro Tutorial" to "Spaceflights"
* Remove mention of eggs 🥚
* Do we mention `__default__` at the best point and, if we do, ensure the explanation is sufficient?
*
