### ISSUE TITLE
Discuss the priority of failing CI

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2340]
## Description

This is solely in the case where CI is failing but no changes have been introduced to the code/manual testing the code still behaves as expected. 

Sometimes CI can fail, seemingly randomly (https://github.com/kedro-org/kedro/pull/1785, https://github.com/kedro-org/kedro/issues/2320). This holds up general progress and delay releases from being shipped. We ought to discuss how much veto power we give the CI in these cases.

We had some several other strong opinions so I've put this forward to tech design - tagging @AntonyMilneQB , @idanov, and @deepyaman here.

My personal opinion is that if the tests can be proven to be failing as a result of the CI, but the element being tested still behaves as it should, the CI should not be a blocker (though resolving the issue should still be of high priority).

**Comment by AntonyMilneQB** [comment]
100% agree with @AhdraMeraliQB here. We are smarter than CircleCI and should use it as a tool, not let it dictate when we do a release.

This might also be handy: https://circleci.com/blog/introducing-test-insights-with-flaky-test-detection/. There's a few features for monitoring tests on CircleCI that we could be using and I think would improve the dev experience quite a bit.

**Comment by merelcht** [comment]
We discussed this issue in **technical design** on the 1st of March:

Opinions on this topic where divided into:

1.  Let's not change anything, because when CI fails there might be something bigger going on than thought at first so we shouldn't merge anything until it's fixed.
2. We should ignore failing tests when we know they're not failing because of the changes in the PR. Merge the PR(s) and then prioritise fixing the tests.
   - In the past ignoring tests has never caused big problems.

Preference among the team was slightly skewed to point 1, however we agreed that in some cases an admin can merge a PR that's blocked by unrelated failing CI. 

Other actions that came from this discussion:

- [ ] Prioritise making our Windows CI more reliable. Write up the issues we're currently seeing and investigate ways of making the CI more robust. We could talk to other teams who run Windows, perhaps Alloy.
- [ ] Move away from CircleCI: as a first step move `kedro-plugins` to Github actions, when that's completed to satisfaction we can more the core Kedro project to Github actions as well.
- [ ] In the meantime see if we can use CircleCI features to help discovering flaky tests.
