### ISSUE TITLE
Remove setuptools from core dependencies

### ISSUE THREAD

**Issue by ZiruiXuQB** [kedro-org/kedro#2350]
## Description
I'm always frustrated when `pip install kedro` upgrades the versions of `setuptools`, `wheel` and `pip`.

## Context
Usually I would not expect `pip install` to upgrade these packages unless I explicitly run `python3 -m pip install --upgrade pip setuptools wheel`.

The behaviour is even more surprising as `kedro` does not give a first impression of a package that is related to packaging or dependency management.

## Possible Implementation
- `wheel` and `pip` dependencies will probably be excluded when `pip-tools` is removed from the core dependencies (by deprecating `kedro build-reqs`)
-  `setuptools` can be moved to an optional dependency, `kedro[package]` to support the functionality of `kedro package`

## Possible Alternatives
n/a

**Comment by datajoely** [comment]
super reasonable suggestion @ZiruiXuQB - I'm actually amazed this hasn't been suggested before!

**Comment by deepyaman** [comment]
I wouldn't move `setuptools` to an optional dependency, but rather remove it altogether. Instead of invoking `setup.py` directly, it's preferable to use `python -m build` (as of PEP 517, PEP 518). However, I suppose then `build` becomes a dependency...

Alternatively, you could just deprecate the `kedro package` command, because all it is is a thin wrapper on top of a `setup.py` invocation. I think I'd recommend this, since Kedro went through the [exercise of evaluating CLI command usage](https://github.com/kedro-org/kedro/issues/1293) and deprecating other thin wrappers; not sure why `kedro package` stats don't show up in that report.

Somewhat relevant (but not a solution): https://github.com/kedro-org/kedro/issues/2280

**Comment by noklam** [comment]
Pinging @astrojuanlu

**Comment by astrojuanlu** [comment]
This is blocked by migrating to `pyproject.toml` (see https://github.com/kedro-org/kedro/milestone/36)

**Comment by noklam** [comment]
@astrojuanlu Can we close this already? I think for `kedro` it is move to `pyproject.toml` so these are only build requirements now?

**Comment by astrojuanlu** [comment]
kedro still has a dependency on pip-tools and setuptools:

https://github.com/kedro-org/kedro/blob/664411d568417d414a8efc848a02b0fb08ce1c80/pyproject.toml#L31-L36

IIUC, when we remove `kedro build-reqs` part of this issue will fix itself.

OTOH, `kedro package` now does not depend on `setuptools` anymore, and `build` does not depend on it either:

https://github.com/pypa/build/blob/381ce789e1662e2e16b0ca4be520cdcf7464f5a3/pyproject.toml#L34

I was under the impression that we needed to wait on #2853 to remove our direct dependency on `setuptools`, but maybe we can proceed already. That would fix the other half of the issue.

**Comment by astrojuanlu** [comment]
Double check `micropkg` though, I recall we use setuptools package discovery. The structure of `kedro micropkg package` could be changed into an src-layout to avoid this, but it would be a breaking change. If that's needed to close this issue though, maybe let's do it ahead of 0.19.

**Comment by astrojuanlu** [comment]
This is the code that uses setuptools on runtime:

https://github.com/kedro-org/kedro/blob/ae5f6ff814203344717a089be2ed3442fe57ccf4/kedro/framework/cli/micropkg.py#L220-L231

**Comment by astrojuanlu** [comment]
Ideas to remove dependency on setuptools:

- In `pyproject.toml`, explicitly declare the packages ("packages = ...") instead of using the autodiscovery ("tool.setuptools.packages.find").
- Alternatively, in the `pyproject.toml` generated by micropkg, add a `[tool.kedro]` section that contains `package_name`, so we don't have to guess it.

**Comment by merelcht** [comment]
Only removing `setuptools` is left to do.

**Comment by astrojuanlu** [comment]
🎉
