### ISSUE TITLE
Use `pyproject.toml` instead of `setup.py` in `kedro package`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2413]
## Description
Inline with modernising the packaging/setup in Kedro to use `pyproject.toml`. 

## Context
Move along with the rest of the python community. 

## Possible Implementation
Ideally implement in a backwards compatible way to look for `setup.py` first and if that's not available use `pyproject.toml` in the `0.18.X` series. Then in `0.19.0` remove support for the `setup.py` way.

**Comment by astrojuanlu** [comment]
In fact, after gh-2568, `kedro package` does not depend on whether the project uses `setup.py` or `pyproject.toml` anymore, since it's a wrapper over [`pypa/build`](https://pypi.org/project/build/):

https://github.com/kedro-org/kedro/blob/2f248a4fc650f44d40323466b18d436024d83c75/kedro/framework/cli/project.py#L152-L163

So I'm not sure there's anything left to be done here.

**Comment by astrojuanlu** [comment]
There is nothing to do here, closing.
