### ISSUE TITLE
`__main__.py` checks wrong attribute in `cli.py`

### ISSUE THREAD

**Issue by sv1990** [kedro-org/kedro#2415]
https://github.com/kedro-org/kedro/blob/884f522d3150b974cab7598cbd2c05fa33343af9/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/__main__.py#L27-L30

In the code snippet above it is checked that `cli.py` contains an attribute `cli` which in my oppinion does not make sense since that attribute is not used in the remainder of the code. I think instead it should check for an attribute `run` since that is returned in the next line. Is that correct?

**Comment by datajoely** [comment]
So this is looking for the run command registered in the click context namespace. It is written this way so that Kedro will auto-detect the out-of-the-box CLI or take an[override via a plug-in or a local defintion](https://docs.kedro.org/en/stable/development/commands_reference.html#customise-or-override-project-specific-kedro-commands) `cli.py` within your own project.

Without modification, this imports the cli namespace from [this location](https://github.com/kedro-org/kedro/blob/884f522d3150b974cab7598cbd2c05fa33343af9/kedro/framework/cli/cli.py#LL46) and then


If you look at this comment at the top:
> ` # fail badly if cli.py exists, but has no `cli` in it `

the `cli` attribute it refers to is a click namespace refers to the [click](https://click.palletsprojects.com/en/8.1.x/) function scope linked above

**Comment by sv1990** [comment]
Thanks for the quick reply. I overlooked that part in the documentation
