### ISSUE TITLE
Compress Sidebar on Docs

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2432]
## Description

Allow the headings in the docs sidebar to be collapsible to that by default the sidebar doesn't need scrolling and all the main sections can be seen at a glance.

**Comment by stichbury** [comment]
I like this! It's subject to us deciding what toolchain we will use to some extent. Also we should consider accessibility concerns before we hide everything behind expandables, but since we are already using them, to some extent, adding more has no major impact. We do need to think it through though.

So yes, I'm definitely in favour of reducing that sidebar, either with a new theme, different IA or both.

**Comment by stichbury** [comment]
We did this in #2480
