### ISSUE TITLE
Enable adding new attributes to datasets

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2440]
## Description
Implement the feature to allow users to add new attributes to datasets. Use the syntax decided in #2439 

- Verify that this works for the datasets preview: https://github.com/kedro-org/kedro-viz/issues/907
- The extra attributes will be consumed by plugins (kedro-viz, kedro-mlflow etc) and not on the Kedro backend

## Context
Sub-task of https://github.com/kedro-org/kedro/issues/1076

To be done after: [Decide on syntax to allow adding new attributes#2439](https://github.com/kedro-org/kedro/issues/2439)

## Open question
Where should the `metadata` (or other name) attribute go? 
- On the individual datasets
- On the `AbstractDataSet`
- On the `DataCatalog` like layers?

**Comment by merelcht** [comment]
I think the handling of the `metadata` attribute should happen on the individual datasets. Any processing of the info in the `metadata` will be done by external plugins and not the Kedro framework itself.

The only complication here is that `layers` are processed inside the `DataCatalog`. It used to be on the individual datasets as well, but was moved to the catalog later on: https://github.com/quantumblacklabs/private-kedro/pull/548/files

If `layers` needs to go under metadata like this:
```yml
my_dataset:
       ....
       metadata:
            kedro-viz:
                 layer: raw
```

We'll need to ensure they're still processed correctly and also make sure the implementation is backwards compatible with having layers outside the metadata key.

**Comment by merelcht** [comment]
Excellent discussion the team had before about exactly this: https://github.com/quantumblacklabs/private-kedro/issues/1148

**Comment by rashidakanchwala** [comment]
_Questions to consider:_
_- Why was layer moved to the DataCatlog originally (in the ticket above)? Is there something that hasn't been addressed?_
This is just my assumption but layers have been on Kedro-viz since 2020 and prior to this there was no other extra information that was passed in catalog from kedro project to kedro-viz, that's why probably there was no need? 

_Are there any oversights on moving the handling of the layer attribute to Viz?_
There will be some modification we will need to do on kedro-viz to read the layers but it should be simple and I don't know if we should make it backward compatible since Kedro is deprecating it @tynandebold , @AntonyMilneQB   -- any thoughts? 

_Are there any other users of the top-level layer attribute?_
I doubt, it seems very specific to Kedro-viz.
