### ISSUE TITLE
Investigate simplifying the api hierarchy

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2441]
## Description
https://github.com/kedro-org/kedro/issues/712 was discussed in Tech design, resulting in several points of discussion and some unaddressed questions. Before any progress can be made, these will have to be addressed.

The outcome of this issue should be a plan on how to proceed with #712.

The key comments will be copied over for reference.

**Comment by noklam** [comment]
> Vomiting some initial thoughts (based on what I remember):
> 
> * A lot of libraries have a top-level `api` module in the package that defines the public API (e.g. `from kedro.api import pipeline`).
> * Some larger libraries take this further by having `api` modules for each submodule. Then, the higher-level APIs can `import *` from each of the submodules.
>   
>   * Personal preference: I like when the imports from each submodule are explicit, instead of using `import *`, because that makes it really difficult to track where some things are actually defined IMO.
> * There are also libraries like https://pypi.org/project/atpublic/ to keep `__all__` more maintainable, though I haven't used it (and honestly only seen it used in one place). from - @deepyaman 

> 

> Overall the only question in my mind here is what exactly the structure should be:
> 1. `kedro.node`, `kedro.pipeline` as per the initial suggestion
> 2. `kedro.something.node`, `kedro.something.pipeline` as per @limdauto's idea that imports from the kedro library would contrast with imports from `kedro.framework.project` (maybe `kedro.library.node`, `kedro.library.pipeline`? I don't like that though)  - from @AntonyMilneQB 

If I summarize it correctly from the long thread. Some of the questions are already answered in the parent issue #712 
There are few options here

1. `kedro.node` , `kedro.pipeline` - top level namespace
2. `kedro.something.node`, `kedro.something.pipeline` - One `kedro` submodule potentially `kedro.api` module that expose all public level API
3. `kedro.sub_module1.api`, `kedro.sub_module2.api` - submodule level API

(1) Maybe the easiest for a user to discover, but I am highly against it because it pollutes the `kedro` namespace. In short it will creates dependencies for all kedro submodules - see https://github.com/kedro-org/kedro/issues/2441#issuecomment-1476484052
(2) I like this option the best so far - compromised and relatively easy to remember.
(3) Overhead is large - Kedro public API isn't that large and I don't feel a strong need for sub-module level API alias.

Independently of the options above
* We should use `__all__` anyway to avoid users importing stuff we don't want.
* This new API should be only user-facing. Any code within the code base should keep the import path.

```python
from kedro.framework.pipeline import Pipeline  # This is correct
from kedro.api import Pipeline  # We shouldn't do this in our codebase because it creates the "every module depends on each other" problem
```

**Comment by merelcht** [comment]
Closing this as well. Like @astrojuanlu mentioned on #712 this is not something we'll be addressing at the moment. If you feel like we should redesign our API, please leave a comment.
