### ISSUE TITLE
Design full Project Creation CLI Flow 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2506]
Parent Issue: #2388 
## Description
Design the full revamped Project Creation CLI flow which includes:
- Add-ons selection (https://github.com/kedro-org/kedro/issues/2850)
- Template selection (e.g. pandas, pyspark, viz)
- Example selection

## Context

- https://github.com/kedro-org/kedro/issues/2388 Outlines the idea of the revamped CLI Flow
- https://github.com/kedro-org/kedro/issues/2838 Describes the new starters that will be created that can be selected as templates and examples during the project creation flow.
- https://github.com/kedro-org/kedro/issues/2850 Contains the design for the add-ons selection

**Comment by yetudada** [comment]
Another requirement from @NeroOkwa: "Making sure Kedro-Viz is discoverable at CLI creation".

**Comment by datajoely** [comment]
Some nice libraries for interactive command line interfaces:

- [InquirePy](https://inquirerpy.readthedocs.io/en/latest/)
- [Textual](https://github.com/Textualize/textual)

**Comment by yetudada** [comment]
**Up for review; will be modified by @amandakys, @astrojuanlu and @merelcht**

## Design considerations 

We will work on the assumption that the user will be able to create a project template in the following ways: 
 - Using the project creation CLI wizard
 - Using the project creation CLI flags
 - Using their custom starters 

These assumptions mean that we should: 

 - Rework what happens when a user runs `kedro new` because the project creation CLI wizard starts running
 - Create new CLI flags to match the project creation CLI wizard 
 - Maintain the current CLI flags that allow users to choose a starter, namely `--starter=<path-to-starter>`, ` --starter=name_of_starter` and `--checkout=version_number`

### What's out of scope for V1?

 - We are not including Airflow and Databricks in this current flow; we will look at this after 0.19.0
 - Perhaps later, we can deprecate the CLI command group, `kedro starter list`, if we assume that users will not want to see _our_ list, but this remains to be verified

## What does the project creation wizard look like? 

The user should: 
 - Run `kedro new`
 - Be asked to provide a project name
 - Be asked if they want example code, i.e. spaceflights
 - Be asked for project add-ons (or tools)

> _Note:_ I've called add-ons, tools. But this can be changed back. 

```
(my-virtual-environment) ➜  kedro new 

Project name
===========
Please enter a human-readable name for your new project.
Spaces, hyphens, and underscores are allowed.

 [New Kedro project]: Customer segmentation 


Example code
============
Would you like to include an example [y/n]: y


Project tools
===========
Here, you can select which tools you'd like to include. 
To read more about these tools and what they do, visit: docs.kedro.org

Tools 
1)  Linting  :  Adds linting with Ruff and Black
2)  Testing  :  Adds testing support with Pytest
3)  Logging  :  Adds more logging options
4)  Documentation  :   Adds documentation support with Sphinx
5)  Data structure  :  Creates a directory structure for storing data 
6)  Kedro-Viz  :  Adds setup for Kedro's native visualisation tool
7)  PySpark  :  Adds support for PySpark

Which add-ons would you like to include in your project? [1-4/all/1,3]: 1,2,7
```

> _Note:_ We don't have a single home which explains all the tools or add-ons, so the documentation home page is linked.   

## What do the project creation CLI flags look like? 

We need to create new ones for the project name (`--name`) and tools (`--tools`) and including example code (`--example_code`).

So it could be something like: 
```
kedro new --name="Customer segmentation" --tools=lint,test,pyspark --example_code=y
```

> _Note:_ We need shorthand names for `--tools`, i.e. linting is `lint`. We also have yet to decide the default behaviour if a user does not indicate one or more flags. We should assume people would use this flow in the CLI, so putting them through the CLI wizard to get the response should not happen.

**Comment by amandakys** [comment]
Following the internal user feedback session on 13/09/2023: 

We presented the following prototype

```
(my-virtual-environment) ➜  kedro new 

Project Name
============
Please enter a human readable name for your new project.
Spaces, hyphens, and underscores are allowed. 
To skip this step in future use --name

[New Kedro Project]: My ML Pipeline 


Project Add-Ons 
================
Select which add-ons you'd like to include. 
To skip this step in future use --add-ons
To read more about these add-ons and what they do visit: kedro.org/

Add-Ons 
1) Lint:        Provides a basic linting set up with Black, Ruff 
2) Test:        Provides basic testing set up with pytest 
3) Log:         Provides more logging options, environment specific,  
4) Docs:        Provides basic documentations setup with Sphinx
6) PySpark:     Provides set up configuration for working with PySpark
8) Kedro-Viz:   Provides Kedro's native visualisation tool 

Which add-ons would you like to include in your project? [None/1-4/1,3/all]: 1,2

Example Pipeline 
================
Select whether you would like an example spaceflights pipeline included in your project.
To skip this step in the future use --example=y/n
To read more about how examples work visit: kedro.org/

Would you like to include an example pipeline? [Y\n]:Y

Congratulations! 
Your project My ML Pipeline has been created in directory /my_ml_pipeline 
You selected the following add-ons: Lint, Test 
It has been created with an example pipeline.
```

We received feedback on the following points: (❓flagged for further discussion) 
1. the name add-ons makes it sound more optional, which can be misleading (possible names: tools, options, utilities, plugins) ❓
2. should we allow users to define preset groups of add-ons?
3. adjusting the copy of the CLI wizard to better highlight that we are recommending tools for certain functionality i.e. Black/Pytest instead of just Lint/Test ❓
4. an interactive playground/sandbox UI for generating kedro new commands in the docs. Allow people to experiment with options and preview what the project would look like. 
5. users suggested that the default state should include examples, but no add-ons, as the most likely user type to use a basic new command is a new command. ❓
6. if the user does not select the testing add-on the example project should not contain tests. (especially because we wouldn't have installed the testing dependencies) 
7. providing a custom flag to bypass the interactive flow and apply defaults to all flags that aren't provided. this will help for programmatic creation, and also expert users who want to skip the flow.  ❓
8. the `--starter` flow should stay independent of the addons flow to allow users to start a project with their own custom project.

**Comment by amandakys** [comment]
Closed as initial design is now 'complete' and follow up work is tracked in #3054
