### ISSUE TITLE
Create new documentation page to show a staged migration from a notebook to a Kedro project. 

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2855]
This is a page 2 from this ticket https://github.com/kedro-org/kedro/issues/2845 and I'll pair with @astrojuanlu later in Q3 to work out an example.

**Comment by stichbury** [comment]
@astrojuanlu This is the ticket to add a notebook for docs about notebooks 🤯

**Comment by astrojuanlu** [comment]
Notebook version of the spaceflights tutorial https://gist.github.com/astrojuanlu/f3e2bc336568a18cc5ca507e05206dd7

Quick and dirty, as notebooks are :) Contains, in order of appearance:

1. Cells on top loading the data with pandas, as it's typically done (these are to be replaced by `catalog.load` eventually)
2. Then the preprocessing part, without functions (this is to be replaced by the functions, to remove duplicated code, and eventually the nodes and pipelines)
3. Then the model training part, that contains the hardcoded list of features (in `X = model_input_table[[...]]`) and the hardcoded `test_size` (these are to be replaced by parameters)

So my recommendation is to work through the Jupyter blog posts we have in the works, and cover (3), (1), (2). Starting (2) is the tricky part, because at that point the user already needs the Kedro project template. (3) can use the `OmegaConfigLoader` exclusively, and (1) a combination of `OmegaConfigLoader` + `DataCatalog`.

**Comment by stichbury** [comment]
I'm tempted to use `nbsphinx` and write this page of the docs in a notebook so it's readable HTML but users can also download it and work with it directly. WDYT, is that asking for trouble?

**Comment by astrojuanlu** [comment]
nbsphinx allows you to have the notebooks without the outputs, then they get executed when the docs are built. this makes version control a bit easier.

in fact, we can have markdown-only notebooks. here's an example I know well: https://github.com/poliastro/poliastro/blob/main/docs/source/examples/analyzing-NEOs.myst.md

(Rendered: https://docs.poliastro.space/en/stable/examples/Analyzing%20NEOs.html)

(Config: https://github.com/poliastro/poliastro/blob/55e96432b27301c5dffb4ef6b4f383d970c6e9c0/docs/source/conf.py#L169-L171)

**Comment by stichbury** [comment]
This was resolved by #3128
