### ISSUE TITLE
Using custom dataset loaders triggers a DeprecationWarning

### ISSUE THREAD

**Issue by zedrdave** [kedro-org/kedro#2882]
## Description
Following deprecation of `kedro.extras.datasets.`, using a custom dataset class triggers a `DeprecationWarning` due to the package search order: https://github.com/kedro-org/kedro/pull/2546#issuecomment-1656791661

## Steps to Reproduce

Define a custom loader class in:
File `utils/loaders.py`:
```
class MyLoader(AbstractDataSet):
    [...]
```

In `catalog.yml`, use custom loader:
```
some_input_df:
  type: utils.loaders.MyLoader
  filepath: somefile.csv
```

Run pipeline node using `some_input_df`

## Expected Result
File gets processed by `MyLoader` with no warning.

## Actual Result
Kedro will output a DeprecationWarning:
```
DeprecationWarning: `kedro.extras.datasets` is deprecated and will be removed in Kedro 0.19, install `kedro-datasets` instead by running `pip install kedro-datasets`.
```

## Your Environment

kedro, version 0.18.11
Python 3.10.11
OS X

## Possible solution

As mentioned in [this thread](https://github.com/kedro-org/kedro/pull/2546#issuecomment-1656791661), the problem likely stems from the current package search order:
`_DEFAULT_PACKAGES = ["kedro.io.", "kedro_datasets.", "kedro.extras.datasets.", ""]`

Local path appears after the deprecated `kedro.extras.datasets.` path, triggering the warning during the search.
Changing to: 
`_DEFAULT_PACKAGES = ["kedro.io.", "kedro_datasets.", "", "kedro.extras.datasets."]`

would likely fix the issue.

**Comment by noklam** [comment]
Thank you for the details report - we will look into it shortly.

**Comment by deepyaman** [comment]
@zedrdave Thanks for flagging! It makes sense why this is getting triggered; the warning is emitted anytime the `kedro.extras.datasets` module is loaded (including to check for the availability of a dataset), instead of only when a dataset is accessed from there.

> As mentioned in https://github.com/kedro-org/kedro/pull/2546#issuecomment-1656791661, the problem likely stems from the current package search order:
`_DEFAULT_PACKAGES = ["kedro.io.", "kedro_datasets.", "kedro.extras.datasets.", ""]`
>
> Local path appears after the deprecated kedro.extras.datasets. path, triggering the warning during the search.
Changing to:
`_DEFAULT_PACKAGES = ["kedro.io.", "kedro_datasets.", "", "kedro.extras.datasets."]`

Unfortunately, I don't think this would be acceptable, because somebody still using `kedro.extras.datasets` vs `kedro_datasets` would have a different precedence order.

Intuitively, I feel the solution should be to just put the warning on the dataset access, or (perhaps easier), keeping track of the `prefix` in https://github.com/kedro-org/kedro/blob/0.18.12/kedro/io/core.py#L414-L418 that's eventually used, and raising the warning if `prefix == "kedro.extras.datasets."`. I can probably take this (unless you want to give it a shot, since you've identified the problem and the relevant code :)).

**Comment by zedrdave** [comment]
@deepyaman Just to be clear, my suggestion would not be to change the precedence order between `kedro.extras.datasets` and `kedro_datasets` (the latter would remain before the former). Merely to move custom datasets (prefix `""`) before `kedro.extras.datasets`, so that if someone is using a custom dataset, it gets loaded before reaching `kedro.extras.datasets` is checked, and no deprecation warning is triggered.

Adding the deprecation warning at dataset access level is certainly a solution, but feels like it might add quite a bit of unnecessary code.

In any case, happy to let you take care of it, since I am not all that familiar with kedro's inner code.

**Comment by merelcht** [comment]
Hi @zedrdave , thanks for flagging this issue. We've discussed it internally and decided to not solve the issue because we will be removing the datasets `kedro.extras.datasets` from the core Kedro library soon and with it the `DeprecationWarning` that's causing the problems for you.
