### ISSUE TITLE
Convert an existing project into a project using Kedro as a Library + Framework

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#2924]
## Description
This follows the insights from #2901; one of the issued flagged is how we make it easier to use Kedro with existing projects. This task focuses on putting yourself into the shoes of our users as they refactor their work into adopting Kedro. 

## Possible Implementation
The scope of this task involves taking this project and converting into a project which uses Kedro as a: 

 - Library (so try to use the ConfigLoader, DataCatalog and Pipeline) 
 - Framework (so try to adopt the framework and project template)

You can work with the post authors, Daisy Wood and Mitchell West. Mitchell additionally added: "Happy to work with the Kedro team for guidance getting our approach up and running if it would be helpful? Next steps for this approach is to hopefully create a standalone python package, so would be great to see what a Kedro implementation would look like." 

## Outcomes

Share your learnings on what steps you took and what the process was like. It would be great to see a process diagram and possible workflow improvements that could be made.

**Comment by noklam** [comment]
# Theme that will not be discussed in this TD
## Parameters
Having `parameters.yml` is the first step but it doesn't end there. You may want to organise your parameters group, but sometimes you found that Kedro will force you to organise it in a way (not intended). i.e. 5. Kedro doesn't support full Python function signature
- Unpack Dictionary https://github.com/kedro-org/kedro/issues/2749
- How to support a function or node that takes position-only + keywords-only argument?

For example
```python
def my_function(a,b, *, c=1, d=2):
    return "something"
```

## Hot-reload
6., 7. and 8. are related to the larger milestone [Improve the usability and debugging experience for Jupyter notebooks](https://github.com/kedro-org/kedro/milestone/38)

**Comment by noklam** [comment]
# Follow up
Development: Address 3. and 4. (create ticket and spec for this)

Documentations: Document clearly what is `pyproject.toml`, How can you change `pyproject.toml` for [non-standard project without `src`](https://github.com/orgs/kedro-org/projects/2/views/19?pane=issue&itemId=20351285)

Current doc: https://docs.kedro.org/en/latest/kedro_project_setup/settings.html#project-metadata

https://github.com/kedro-org/kedro/blob/4563a4c609cf808e9087561af5619f143ba3fcff/kedro/framework/startup.py#L112-L123

Generate `source_dir` in `kedro new`, and give it a default `src`.

- [ ] https://github.com/kedro-org/kedro/issues/2962
- TBD in Tech Design

**Comment by noklam** [comment]
2023-08-23

Discussion for DataCatalog path conversion issue
- Should we move this to `DataCatalog.from_config` and add a new argument `data_source` (similar to `conf_source`)?
- Or should we change `ConfigLoader` because `DataCatalog` expects a `dict` and the responsibility to read config falls into `ConfigLoader`? It's blurry because it's not exactly "reading" config, it changes the content of `catalog.yml`
- Or `DataCatalog._convert_path` or `DataCatalog.convert_path`

```python
conf_catalog = config_loader["catalog"] # config
conf_catalog = _convert_paths_to_absolute_posix(Path("../../").resolve(), conf_catalog) # config/catalog
catalog = DataCatalog.from_config(conf_catalog) # catalog
catalog.load("example_data")
```

- @SajidAlamQB and @ankatiyar thinks that configs should be handle by `config_loader` because it clarifies the responsibility of reading config.
  - Some idea about introducing a new parameters `data_source`, `root` etc in `ConfigLoader` and resolve it automatically with `config_loader["catalog"]
- @deepyaman, @astrojuanlu ,@noklam and @amandakys favors to change `DataCatalog.from_config(new_argument)`
  - options include `data_source` or `root`
  - @astrojuanlu also suggested that we may even provide specific pattern to merge. ie.e `DataCatalog.from_config(file_parameters=["filepath", "path"])`
 - @amandakys and @deepyaman point out that if we choose to do it in `config_loader`, user will be forced to use config loader with `DataCatalog`.
- The decision is to change `DataCatalog.from_config`, we haven't decided what should be the name of the argument.

**Comment by noklam** [comment]
- [ ] https://github.com/kedro-org/kedro/issues/2962
- [ ] https://github.com/kedro-org/kedro/issues/2965
- [ ] #2819

**Comment by noklam** [comment]
Closing as the exercise is finished and we identified a few key issues. Relevant comments are spread into these issues: https://github.com/kedro-org/kedro/issues/1460, https://github.com/kedro-org/kedro/issues/2819#issuecomment-1669771871
