### ISSUE TITLE
Improve "404 not found" pages on the documentation

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2951]
## Description
#2486 fixed #2464, and the current situation is much better than what we had.

However, navigating to old versions of the docs is hard: https://github.com/readthedocs/readthedocs.org/issues/10643

It would be better if 404 pages reflected the navigation structure of each version.

## Context

Used very often by @stichbury and the rest of the team to see how a specific page used to look.

## Possible Implementation

I _think_ there's an undocumented feature of Sphinx in that one can add a `404.md` page to the docs (if it's documented, I haven't found it). That should be a solution going forward.

For older versions, it's more complicated. We could create a branch in the repository for each version we want to amend (not necessarily all of them) that adds such a page.

Apart from all this, we should probably keep the `sphinx-notfound-page` extension for the time being.

**Comment by astrojuanlu** [comment]
Examples:

- https://github.com/wpilibsuite/frc-docs/blob/main/source/404.rst
- https://github.com/ansys/ansys-sphinx-theme/blob/main/src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/404.rst

(By the way, this explanation is top notch ⭐ https://sphinxdocs.ansys.com/version/stable/user_guide/404_page.html)

**Comment by stichbury** [comment]
@astrojuanlu Given the discussion in #2980 should we now focus our attention on branches for adding 404 pages just for v 0.17.7 and for 0.18.0 onwards (with possible omission of 0.18.0-0.18.4 as they're not indexed)?

**Comment by astrojuanlu** [comment]
Indeed, we can do a proof of concept with 0.17.7, and if it works extend it to 0.18.5 onwards.

For now, let's add a `404` page in the `main` branch, so it works with `latest` and soon `stable` too.

**Comment by astrojuanlu** [comment]
> Is it possible to do a "did you mean?" page on 404 which offers URLs suggestions? This is my biggest gripe doing user support as I search for page which no longer exists on a newer version.

_Originally posted by @datajoely in https://github.com/kedro-org/kedro-viz/issues/1474#issuecomment-1819609013_

**Comment by astrojuanlu** [comment]
Missing:

1. Examples of this happening in the wild
2. A better definition of the outcome

**Comment by astrojuanlu** [comment]
cc @stichbury could you help me with (1)? and I'll describe (2) in a bit more detail

**Comment by stichbury** [comment]
Some ideas for examples in the wild:

1. This is quite nice because it brings up an explanation and a search box, prepopulated with the URL you tried to find, and the results of that search for you to choose from:

<img width="863" alt="image" src="https://github.com/kedro-org/kedro/assets/5180475/5c3ad4b2-0bab-4e33-b4ce-de543cc3b3fa">

(results from https://ably.com/docs/general/push/publis?q=dafd)

---

2. Basic search bar (not populated) to help move people onwards
<img width="885" alt="image" src="https://github.com/kedro-org/kedro/assets/5180475/00259492-724f-4929-95eb-7121e53caabd">

---

3. From ARM developer docs
 
<img width="985" alt="image" src="https://github.com/kedro-org/kedro/assets/5180475/b74ba06f-7363-4156-86ab-56039783adc7">

---

4. This is very basic but gives a contact (we could push people at Slack)

<img width="411" alt="image" src="https://github.com/kedro-org/kedro/assets/5180475/c779e7ae-cf67-4908-ad4b-05a0ed2b9f2a">

**Comment by astrojuanlu** [comment]
We'll possibly need to add custom tracking for those errors https://community.heap.io/using-the-product-46/possible-to-track-web-errors-like-400-401-403-554?postid=1542#post1542

**Comment by astrojuanlu** [comment]
I initially described the problematic navigation in https://github.com/readthedocs/readthedocs.org/issues/10643#issue-1854507921, but with the new add-ons, the logic has changed: https://github.com/readthedocs/addons/issues/223

As a result, now it's impossible to land in a 404 page when switching versions. The downside though is that navigating across versions is more difficult now.

**Comment by stichbury** [comment]
Looking at this again and I'm not convinced there's anything more we can do. Would adding a `404.md` page have any advantages over the current situation of using the extension, given the add-ons have changed the logic of this situation? I'm happy to try it if so, otherwise let's close this.

**Comment by astrojuanlu** [comment]
Indeed, I think there's not much for us to do here until we have more clarity on https://github.com/readthedocs/addons/issues/211. Closing for now.
