### ISSUE TITLE
Make `source_dir` discoverable and document how to use this for non-standard project structure

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2962]
## Description

Related to https://github.com/kedro-org/kedro/issues/2553
>Documentations: Document clearly what is pyproject.toml, How can you change pyproject.toml for [non-standard project without src](https://github.com/orgs/kedro-org/projects/2/views/19?pane=issue&itemId=20351285)
Current doc: https://docs.kedro.org/en/latest/kedro_project_setup/settings.html#project-metadata

We never document it clearly how to use `source_dir`. It's a misconception that `src` is a must for kedro-project.
https://github.com/kedro-org/kedro/blob/4563a4c609cf808e9087561af5619f143ba3fcff/kedro/framework/startup.py#L112-L123

## Context

Users misunderstood that `src` is a must for Kedro Project, it can be configured already but we never document it clearly.

## Possible Implementation

- Add documentations, i.e. How to work with Kedro if I have my own project structure already
- Add `source_dir=src` to `pyproject.toml` by default to make this discoverable.

**Comment by astrojuanlu** [comment]
Ambivalent about this. After https://github.com/kedro-org/kedro/issues/2280#issuecomment-1437071618 is complete, every Kedro project will be a standard Python library, so we can defer to standard source discovery mechanisms for this without the need of `source_dir`.

I would go as far as saying that we should deprecate it completely.

**Comment by noklam** [comment]
Interesting, I am not aware of these discussion with `pyproject.toml`. Questions:
1. What's the responsibility of the two `pyproject.toml`
2. Currently `kedro pipeline create` or `kedro run` relies on the `source_dir` definition - how would it be changed if we are going to deprecate this?

Maybe we also need to update the logic of https://github.com/kedro-org/kedro/blob/5925b0356ec2a3c922e042154d63725af25db3fa/kedro/framework/startup.py#L37

especially we want to enable `kedro run` anywhere within a project. Having two `pyproject.toml` would cause issue immediately I think.

If we are going to deprecate it, I think we need to have a clear plan. I assume this won't happened before 0.19, do you think we should at least document it?

**Comment by astrojuanlu** [comment]
> What's the responsibility of the two `pyproject.toml`

The root one is the one used by Kedro to store "build config" (using #2434 terminology), the one inside `src` is the direct replacement for `setup.py`. But the idea is to merge both, which we'll do for 0.19.0 because it's a breaking change (see #2926).

> Currently `kedro pipeline create` or `kedro run` relies on the `source_dir` definition - how would it be changed if we are going to deprecate this?

Yeah that's the big question, we need to see if we can use native mechanisms to "discover" where the source is. My "let's deprecated `source_dir`" message is dependant on that, we haven't yet even started analyzing the technical feasability of it.

**Comment by noklam** [comment]
> Ambivalent about this. After https://github.com/kedro-org/kedro/issues/2280#issuecomment-1437071618 is complete, every Kedro project will be a standard Python library, so we can defer to standard source discovery mechanisms for this without the need of source_dir.

Assume #2975  and #2926 is merged, which handle a breaking change for `kedro package`. So we are not moving away from the "src" layout. You are proposing
- Deprecated `source_dir` and use standard python package [Ticket to be created]

What would be the alternative of `source_dir`? Is it [tool.setuptools.packages.find] https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html?

**Comment by astrojuanlu** [comment]
Trying to sort my thoughts here without opening a can of worms.

https://github.com/kedro-org/kedro/issues/2975 means that we would be moving to an `src`-layout, because at the moment we have something "weird", see https://github.com/kedro-org/kedro/issues/2280#issuecomment-1437071618.

Regardless of that change, setuptools (the backend we chose for starters) has always been able to locate the packages because we are relying on setuptools automatic package discovery https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout

https://github.com/kedro-org/kedro/blob/a6a5a4ac00ceeb697371b9caff52955dbda5fa66/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/pyproject.toml#L10-L11

After we move to an `src` layout, this will become

https://github.com/kedro-org/kedro/blob/d5f4ed70389ce59963798e7bc15e601fd3191ca8/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/pyproject.toml#L31-L33

Hence the `src` is already there.

When I (hastily) wrote my message I thought that maybe there was a standard mechanism for package discovery. But it turns out it was left out of PEP 621 on purpose https://peps.python.org/pep-0621/#specify-files-to-include-when-building

So, I only see two paths:

1. We keep `package_name` and `source_dir` in `[tool.kedro]`, just like we've always done. But if the user changes those, they probably need to change the `[tool.setuptools.packages.find]` table as well, which feels redundant.
2. We marry ourselves with setuptools and rely on setuptools package discovery to locate the source code. The disadvantage is that it will make supporting other build backends, like Poetry #1722, flit, Hatch, or PDM, difficult.

Maybe the best thing is to keep some redundancy and not do any dramatic changes for now.
