### ISSUE TITLE
Remove the environment default for ConfigLoader

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2971]
### Context
See #2819 and more

Currently ConfigLoader assume `base` and `local` exist, but for single config use cases ( a notebook) it's not relevant.

### Requirements
- Backward compatible
- Enable use of OmegaConfigLoader without environment

### Current workaround
```python
OmegaConfigLoader(conf_source=".", base_env=".", default_run_env=".")  # To use this in a notebook
```

### Potential Options:
1. Change defaults to "." and change `settings.py` default to "base" and "local" (and starters)
2. Change defaults to "." and change `KedroSession.create`

```python
settings.CONFIG_LOADER_CLASS
return config_loader_class(
    conf_source=self._conf_source,
    env=env,
    runtime_params=extra_params,
    **settings.CONFIG_LOADER_ARGS,
)
```

```python
# Maybe update this in `session.py`?
config_loader_args = {"base_env"="base", "default_run_env"="local"}
config_loader_args.update(settings.CONFIG_LOADER_ARGS) # Overwrite if any
return config_loader_class(
            conf_source=self._conf_source,
            env=env,
            runtime_params=extra_params,
            **config_loader_args,
        )

# Original
settings.CONFIG_LOADER_CLASS
return config_loader_class(
    conf_source=self._conf_source,
    env=env,
    runtime_params=extra_params,
    **settings.CONFIG_LOADER_ARGS,
)
```

I prefer 2. and we can do it now instead of waiting 0.19 cc @merelcht

_Originally posted by @noklam in https://github.com/kedro-org/kedro/issues/2819#issuecomment-1690265666_

Option 3:  
Use `_ProjectSettings` to bake framework assumption.

https://github.com/kedro-org/kedro/blob/d3171f1fc12292adc90a59fbb9ad357cbab0a906/kedro/framework/project/__init__.py#L102-L107

### Additionally
We should clean up the test for config when `local` isn't a necessary requirement. This can be consider as a separate ticket but probably best to do it together.

**Comment by noklam** [comment]
We should also make sure it works even if user provide a relative path. To do that we may need to do a `.resolve()` behind the scene.


> 
> [#2819 (comment)](https://github.com/kedro-org/kedro/issues/2819#issuecomment-1669771871) Additionally, we may always do a `resolve` in ConfigLoader so even if user provide a relative path it would work. I will add this comment to #2971, depends on the implementation we may avoid this completely with the new `root` argument.
> 
> This ticket will remains as a clean up ticket.
> https://github.com/kedro-org/kedro/issues/2912#issuecomment-1698979651

**Comment by noklam** [comment]
> ValueError: Duplicate keys found in /Users/Nok_Lam_Chan/tmp/pandas-iris/conf/local/parameters.1.yml and /Users/Nok_Lam_Chan/tmp/pandas-iris/conf/base/parameters.1.yml: random_state, target_column, train_fraction

The error is confusing if user define a base_env="." and default_run_env="local". This happen because "." will catch both `base` and `local` due to the pattern `**/catalog*`. We should improve the error message to highlight the current environment. In addition, we can make it more explicited, i.e. `Duplicated keys are not allowed in the same environment`

Noted that duplicate value from other environment is OKAY, this is the purpose of the environment to override stuff like `credentials`.

**Comment by merelcht** [comment]
I'm in favour of removing the `base` and `local` defaults from the `OmegaConfigLoader` and instead adding these in the session. 

One concern I have though is around the user experience when moving from just using the `OmegaConfigLoader` as library component to then using the parts of the framework where the session comes in, e.g. `%reload_kedro` line magic, `session.run()` and `kedro run` from the CLI. When users use the library component there will not be any assumptions about configuration environments anymore after this change, but when a user then switches to using more framework stuff they'll find this assumption inside the session. They can update `settings.py` to set the `base_env` and `default_run_env` to something else, but it might be confusing that the setup they used before doesn't immediately work with the full framework. I see two options to solve this:

- Add a very descriptive migration guide from using the library components to then using the full framework which includes the session + elaborate [the chapter on configuration environments](https://docs.kedro.org/en/stable/configuration/configuration_basics.html#configuration-environments)
- Remove the assumption of having two configuration environment by default all together, which is what @noklam mentioned in the comment above. A user would be able to enable config environments through e.g. `settings.py`, but by default they don't have to change anything. 
(-  Actually, a third option could be @noklam 's first option in the ticket description: Change defaults to "." and change settings.py default to "base" and "local" )

I have a slight preference for keeping the two configuration environment setup by default inside the framework, because it's aligned with the best practices that Kedro promises to introduce to ML projects.

**Comment by astrojuanlu** [comment]
Thanks for the analysis @merelcht 

> I have a preference for keeping the two configuration environment setup by default inside the framework, because it's aligned with the best practices that Kedro promises to introduce to ML projects.

Is this option (2) among the three you listed?

**Comment by astrojuanlu** [comment]
> I imagine the flow from library -> framework will still involve kedro new most likely.

I'm not so sure. The moment you start populating your directory, `kedro new` becomes cumbersome.

**Comment by noklam** [comment]
@astrojuanlu `kedro new` maybe too rigid, let say it will requires copy and paste the `settings.py` and `pipeline_registry.py`  or a more automated way (through some `kedro` command to create these templates). In any case we can included the commented default in the `settings.py`.

**Comment by astrojuanlu** [comment]
To summarize previous discussions, @merelcht 's summary on https://github.com/kedro-org/kedro/issues/3029#issuecomment-1749134347 gives the way forward: let's keep the assumption of 2 environments, let's make `OmegaConfigLoader` blind to our base+local framework choice, and let's make this choice explicit in `settings.py`.

**Comment by noklam** [comment]
@astrojuanlu Can I ask for an update of this ticket? Which options are we going to implement?

I am slightly confused with this statement since this ticket propose removing the default envs.
> let's make OmegaConfigLoader blind to our base+local framework choice, and let's make this choice explicit in settings.py.

1. Do we remove the default env for OmegaConfigLoader?
2. Do we change any default settings in framework? 
3. Make the env explicit in `settings.py` (updating the template basically)


My answer to this is all YES but it will be good to double check. If we only do 3 but not 2, it will be a breaking change (maybe that's fine).

Doing 2 without 3 is fine, it's doesn't change anything but it gives users more information what's the default and easier to change them if needed.

**Comment by astrojuanlu** [comment]
> 1. Do we remove the default env for OmegaConfigLoader?

Not sure what "remove" means in this case, but the end goal is that the user can do

```
conf_loader = OmegaConfigLoader(conf_source=".")
```

(in a REPL or a script) and it works without `base` and `local` directories. Hence no need to add `base_env=".", default_run_env="."` too.

> 3. Make the env explicit in `settings.py` (updating the template basically)

In principle yes. That's what @merelcht said in #3029:

> `settings.py` is a good place to keep the defaults, because it's visible to users and this group has experience with updating that file.

Does it make sense?

> Doing 2 without 3 is fine, it's doesn't change anything but it gives users more information what's the default and easier to change them if needed.

As far as I understand, (3) was already decided (see above).

> 2. Do we change any default settings in framework?

I'm not fully aware of the implications of doing or not doing this.

> If we only do 3 but not 2, it will be a breaking change (maybe that's fine).

That's okay but if we can easily avoid it we should try. It will make upgrading to 0.19 from 0.18 easier, right?

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro/pull/3311
