### ISSUE TITLE
Merge pyproject.toml files for starters in line with python src-layout

### ISSUE THREAD

**Issue by DimedS** [kedro-org/kedro#2975]
## Description

Continuation from #2280.

The template project and starters currently contain two `pyproject.toml` files, one in the `root` directory and another in the `src` folder. This arrangement is not aligned with the python `src-layout` package structure. The two files should be merged into a single file in the `root` folder. This breaking change should be associated with the Kedro 0.19 release because it will affect `kedro package` command.

**Comment by astrojuanlu** [comment]
https://github.com/kedro-org/kedro/pull/2926 did this for the Kedro default template, now this needs replication on the starters 💪🏽

**Comment by SajidAlamQB** [comment]
This issue is blocking the PySpark add-ons work, https://github.com/kedro-org/kedro/pull/3169, specifically with the spaceflights-pyspark starter which needs to align with the core template structure for it to work properly. I spoke to @DimedS and he said this needs to be merged when we release 0.19.0 but is there a way to get this out earlier? 

Maybe we just do it for spaceflights-pyspark for now? https://github.com/kedro-org/kedro-starters/pull/164

What do others think? @DimedS @astrojuanlu @merelcht

**Comment by DimedS** [comment]
> 
> What do others think? @DimedS @astrojuanlu @merelcht

In my opinion that ticket is continuation of https://github.com/kedro-org/kedro/pull/2926 that Juan Lu merged into develop because it's a breaking change need to be in 0.19 release. But looks like that we need to update starters now (before kedro 0.19) to be able to continue development smoothly.
