### ISSUE TITLE
Add a deprecation notice to signal the archiving of starters + new project creation flow

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3114]
## Description
In Kedro `0.19.0` we're removing some of the starters and introducing a completely new project creation flow. We should add warnings/info to our users ahead of this so they know this flow will change. 

## Context

- [Introducing Utility Modules to Kedro ](https://github.com/kedro-org/kedro/issues/2388)
- [Remove "non-unique" starters](https://github.com/kedro-org/kedro/issues/3113)

## Possible Implementation
- Add a temporary message in the `kedro new` flow that explains the changes that are coming. 
- Update`kedro starter list`  and add (deprecated/archived) to the starters that will be archived in #3113

**Comment by astrojuanlu** [comment]
Bringing here some concerns that @datajoely raised on #3173:

> So I want to strongly argue we shouldn't delete the empty pyspark starter- the verticals need any empty template to build off

We would be archiving the old starters and not removing them, so as far as I understand Kedro 0.18 with the old starters will keep working for the time being. Are we missing something?

> can you follow all the add on steps from a single command?

Again, as far as I understand, the plan is to make the `kedro new` commands have CLI flags so that it's possible to completely skip the interactive flow https://github.com/kedro-org/kedro/issues/3054#issuecomment-1750416068

> when a flag isnt chosen, the user will go through those steps of the interactive flow

(and by omission, when all flags are chosen, no interactive flow will appear)

More broadly, this breaking change will require downstream projects to adapt to the new way, but we think the end result is going to be superior to what we have nowadays. Please let us know your thoughts on this thread.

**Comment by datajoely** [comment]
* apologies for linking internal, hopefully this is all open early next year *

So if you look at how an alloy app is configured here, Alloy retrieves the cookiecutter template directly 

https://brix.quantumblack.com/products/alloy/docs/01_intro/key_concepts/#app

If you drop this from 0.19.x there will be barrier for Verticals adopting the latest version of Kedro
