### ISSUE TITLE
Enable Dark Mode in docs page

### ISSUE THREAD

**Issue by JaynouOliver** [kedro-org/kedro#3179]
https://docs.kedro.org/en/stable/#
![image](https://github.com/kedro-org/awesome-kedro/assets/88646338/ca482a72-0cd7-4fca-a8a9-e9019788bd06)

It is quite difficult to view the page in light mode in dark. Although we all use an extension but it is better to have a dark mode button that can switch the color

**Comment by PranavJayachandran** [comment]
I am interested. Can you assign this issue to me?

**Comment by astrojuanlu** [comment]
Hi @JaynouOliver, @PranavJayachandran, thanks for your interest! Note that Kedro uses sphinx-rtd-theme at the moment, so for us to have a dark mode we would have to either

- Contribute that upstream https://github.com/readthedocs/sphinx_rtd_theme/issues/224 (issue opened in 2015), or
- Adopt a completely new Sphinx theme https://github.com/kedro-org/kedro/issues/2394 

Feel free to work on any of these, no need to get assigned to it.

**Comment by astrojuanlu** [comment]
Finally, in our opinion this is a difficult task so we are explicitly not labeling it as Hacktoberfest.

**Comment by JaynouOliver** [comment]
Sure, I will a look upon it and start working on it. Thank you for providing me the details.

**Comment by JaynouOliver** [comment]
> Finally, in our opinion this is a difficult task so in principle we are not labeling it for Hacktoberfest. Unless we see a mostly-ready pull request on time, of course!

Sure, I am not doing this for the sake of Hacktoberfest, nor did I mention it anywhere to get the issue labelled. I was actually going through the docs when I struck upon this idea, thanks a lot

**Comment by stichbury** [comment]
I'm really pleased to see this. However, one caveat is that we have some outstanding design changes to come in the docs. The ticket is still awaiting our team to look at it https://github.com/kedro-org/kedro-viz/issues/1474 but there will be a redesign in future, so your work could be short-lived if we move to a different theme or even build tool when it is addressed.

**Comment by JaynouOliver** [comment]
Ok I didn't knew about that. How much time may that take to get deployed to production?

**Comment by stichbury** [comment]
@JaynouOliver At present, it's not on our priority list (based on feedback from user research). We have a Kedro 0.19 release to come out first and then we'll circle back to docs redesign. So there will not be any updates to switch from our current theme in 2023. 

That probably isn't very helpful since it means you risk doing work now that will be brought into Kedro but may drop out again when we do decide how to proceed with a new theme/updates to current them/updates to toolchain. However, I would say that the Sphinx RTD theme maintainers would probably still appreciate a dark mode contribution because regardless of whether Kedro continues to use it, others will.

**Comment by JaynouOliver** [comment]
So what shall I do? shall I proceeded with the code?

**Comment by astrojuanlu** [comment]
Go ahead @JaynouOliver ! As long as we don't change the theme, we'll be happy to have a look at the contribution.

**Comment by stichbury** [comment]
@JaynouOliver I can't really decide for you because I can't commit your time 😄 but if you want to make a contribution for dark mode then it would be welcome. We could potentially use it until such time as we redesign, and maybe after, but cannot guarantee it.

**Comment by JaynouOliver** [comment]
ok

**Comment by stichbury** [comment]
Closing this ticket because it will form part of a broader update to the documentation design covered by https://github.com/kedro-org/kedro-viz/issues/1474 (and if completed standalone would cause more problems than it solves because of https://github.com/kedro-org/kedro/issues/3416).

I will note that dark mode is something to add as a requirement when we cover the redesign.
