### ISSUE TITLE
(security) Fix Arbitrary File Write via Archive Extraction

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3473]
## Description
Flagged by Snyk as Medium priority

## Context
https://github.com/kedro-org/kedro/blob/main/kedro/framework/cli/micropkg.py#L395

<img width="1189" alt="Screenshot 2024-01-03 at 15 57 53" src="https://github.com/kedro-org/kedro/assets/49397448/65f69bda-9410-40a1-ae0e-e81bbf4cf679">

## Possible Implementation
<img width="832" alt="Screenshot 2024-01-03 at 16 00 10" src="https://github.com/kedro-org/kedro/assets/49397448/4bd3bb00-b2a7-4e2f-9d63-678c26cb2eaf">

**Comment by ankatiyar** [comment]
@AhdraMeraliQB @merelcht 
This issue, I believe, was already fixed by https://github.com/kedro-org/kedro/pull/2180. We do now check if all the members of the tar file to be extracted are contained within the directory. Snyk, however, complains still about this line - https://github.com/kedro-org/kedro/blob/e187dca1a5546a0a87f609682e87245f362e65f8/kedro/framework/cli/micropkg.py#L398
The `path` here is sanitised. I don't think there's much more to do here but would like to hear your thoughts!
