### ISSUE TITLE
Create Developer Docs [PARENT TICKET]

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#3487]
## Description

As new features are introduced and the codebase grows, it's important to document the implementation of different components, in the interest of preserving and consolidating knowledge across the team. They should document the execution flow, and record any design/architecture decisions made during implementation. These will also serve as a touch point for feature addition/extension and refactoring.

This isn't truly an issue that can be fully complete, as the project will (hopefully) continue to grow. Considering this, this issue should be considered fulfilled when every reasonable component within the codebase _at the time of the most recent release_ is adequately documented. After 

Outstanding actions:
- [x] Decide on where to host these docs, CC @astrojuanlu -> GH Wiki
- [ ] Curate a list of components requiring documentation. This should include all plugins, starters (where necessary), kedro-viz and kedro framework (this repository)

When a component is selected for documentation, create a spin-off issue, and record it against the relevant component in the list below:

### Documenting:
When documenting, the goal is to be able to discern:
1. The purpose of the piece of code
2. How it achieves this
3. The path of execution and flow of information (e.g user input)
4. How is the component accessed? (Called by other kedro process/cli command/plugin/python api e.t.c)
5. Are there any guardrails/work-arounds/ try-catch clauses/custom error handling/non-standard coding decisions? Document why
6. Does the code make any assumptions? Document these

### List of components to document (incomplete):
- [x] `kedro new` workflow - https://github.com/kedro-org/kedro/issues/3488
- [ ] `kedro run` workflow
- [ ] kedro-airflow
- [ ] kedro-docker
- [ ] kedro-telemetry
- [ ] Kedro starters
- [x] GH Actions setup ?
- [ ] ...

**Comment by stichbury** [comment]
Can I request that before you start writing developer docs that you agree on a common template for each type of docs (requirements, architecture, technical design) and keep these as lightweight as possible. Maybe have them as tables or bullet points where you can. Internal developer docs are _notoriously_ difficult to keep up-to-date because they slip out of visibility and attention, so you should have a common and easy way to write them and update them.

I also suggest the GitHub wiki unless they need to be kept internal to the team since this is an easy way to keep docs together (we already have some contribution guides there) and doesn't split our content over any other platforms.

**Comment by astrojuanlu** [comment]
> I also suggest the GitHub wiki unless they need to be kept internal to the team since this is an easy way to keep docs together (we already have some contribution guides there) and doesn't split our content over any other platforms.

+1. And I don't think these need to be kept internal, everybody will benefit from having these docs public.

**Comment by merelcht** [comment]
We won't be tackling this as Sprint tasks, but instead documenting implementation should be part of the regular workflow of every team member.
