### ISSUE TITLE
Clarify docs around custom resolvers

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3524]
## Description

https://docs.kedro.org/en/stable/configuration/advanced_configuration.html#how-to-use-custom-resolvers-with-omegaconfigloader two problems:

1. for a newbie, it's not clear where the code should go (https://linen-slack.kedro.org/t/16316616/hello-this-is-my-grid-parameter-tuning-options-grid-batch-si#bc370de6-d106-45ef-9cb0-a3a79baa9e09)
2. the code snippet mixes library code with REPL code, which makes it very confusing

**Comment by ElenaKhaustova** [comment]
After looking through the described problems, the following was concluded:

1. We have two sections in the docs touching custom resolvers: [Advanced configuration without a full Kedro project](https://docs.kedro.org/en/stable/configuration/advanced_configuration.html#advanced-configuration-without-a-full-kedro-project) and [Advanced configuration without a full Kedro project](https://docs.kedro.org/en/stable/configuration/advanced_configuration.html#advanced-configuration-without-a-full-kedro-project)
2. Shared confusion about placing the code from [here](https://linen-slack.kedro.org/t/16316616/hello-this-is-my-grid-parameter-tuning-options-grid-batch-si#bc370de6-d106-45ef-9cb0-a3a79baa9e09) happened because we provided an example from `Advanced configuration without a full Kedro project` section which doesn't require placing code into any particular place as Kedro project is not needed.
3. `Advanced configuration without a full Kedro project` describes well where to place the code with extensive examples.
4. The code snippet mixes library code with REPL code in `Advanced configuration without a full Kedro project` indeed looks confusing.

From the above, the following changes were implemented:

Updated Advanced configuration without a full Kedro project docs section:
- clarified that code can be run just as a Python script as a full Kedro project is not required;
- split the code snippet from the output for clarity.

@astrojuanlu
