### ISSUE TITLE
Include ipylab dependency for %load_node in Docs and Requirements

### ISSUE THREAD

**Issue by DimedS** [kedro-org/kedro#3643]
## Description
To enhance user experience with the new `%load_node` magic command in Jupyter notebooks, will be nice to note the requirement of installing `ipylab`. We should consider explicitly mentioning this dependency in the documentation. Additionally, integrating `ipylab` into the `requirements.txt `of Kedro templates and starters could streamline the user flow, ensuring a smoother setup process.

Upon creating a project using `kedro new` and installing the dependencies from `requirements.txt`, which included 
```
ipython>=8.10 and 
jupyterlab>=3.0, 
```
an error was encountered when attempting to execute the `%load_node` command in a Jupyter notebook. The error indicated that `ipylab` was missing, highlighting the necessity for its inclusion in the setup process.

## Your Environment
* Kedro version used: last version, main branch
* Python version used (`python -V`): 3.10
* Operating system and version: MacOS

**Comment by noklam** [comment]
I think we should leave notebook/lab dependencies in starters, because we don't know if users are going to user notebook or lab and we shouldn't force them. We can include this in starter to make it easier for them, but this leave the flexibility if they need to remove it later.

`kedro[jupyter]` however only includes `ipylab`, in theory it also requires Jupyterlab or notebook>7.0. So my proposal is to make this into the starters:


```
ipython>=8.10 and 
jupyterlab>=3.0
kedro[jupyter]
```
