### ISSUE TITLE
ShareMemoryDataset does not have `exists()` method

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3703]
## Description
![image](https://github.com/kedro-org/kedro/assets/18221871/19ecb244-127e-4ffd-82c8-f2854ae83459)

## Context
Unclear, the `SharedMemoryDataset` is implemented by the core team and generating warning when run with `ParallelRunner`, is this false alarm or something we need to address? Cc @merelcht 

## Steps to Reproduce
I was testing something else and see the warning with this command:
`pytest tests/framework/session/test_session_extension_hooks.py::TestNodeHooks::test_on_node_error_hook_parallel_runner`

# Possible Solution:
https://github.com/kedro-org/kedro/blob/0fc8089b637a0679f71e2bddc91f0676fc2914a2/kedro/io/memory_dataset.py#L74C1-L75C40
We have a simple check in `MemoryDataset`, we could implement simliar logic for `ShareMemoryDataset`.

Check whether it makes sense to have an `_exists()` method for `SharedMemoryDataset`. If not: update the logging level to be of `DEBUG`.

**Comment by noklam** [comment]
@merelcht Haven't look into this in details, would the alternative be changing that WARNING message to `INFO` instead?

**Comment by merelcht** [comment]
Reported again recently: https://github.com/kedro-org/kedro/issues/4060

Updated the scope to double check where `exists` is called and if it makes sense to implement this method on `SharedMemoryDataset`.

**Comment by felixscherz** [comment]
Hi, I investigated this for a bit and I believe the issue is that `SharedMemoryDataset` delegates most methods to the underlying `MemoryDataset` via `__getattr__`.
https://github.com/kedro-org/kedro/blob/56e56a783e4b79e96d09c20918a23bb3e11976d1/kedro/io/shared_memory_dataset.py#L33-L37

However, `__getattr__` is only called for attributes that do not exist on the object and since `SharedMemoryDataset` inherits `AbstractDataset._exists` `__getattr__` is never called.

We could implement `_exists` on `SharedMemoryDataset`, we would have to handle the case where `self.shared_memory_dataset` is `None` (return `False` in this case?):

```python
    def _exists(self) -> bool:
        if not self.shared_memory_dataset:
            return False
        return self.shared_memory_dataset.exists()
```

I'm happy to submit a PR implementing this:)
