### ISSUE TITLE
[DataCatalog]: Error message is confusing when using `DataSet` instead of `Dataset`

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#3909]
## Description
There is confusion between `DataSet` and `Dataset` terminology, and the error message is not informative when using old naming. They have been renamed in 0.19, but people miss that fact when switching to the new version.

Relates to https://github.com/kedro-org/kedro/issues/2401

## Context
Example of the current error message:

```shell
DatasetError: An exception occurred when parsing config for dataset 'companies':
Class 'pandas.CSVDataSet' not found, is this a typo?
```

**Comment by datajoely** [comment]
I wonder if we could auto-fix this with a big warning

**Comment by astrojuanlu** [comment]
I have a couple questions on this one:

- As far as I understand, projects created with our starters have a `kedro_init_version` that limits what version of Kedro can be used. If, say, someone created a project with Kedro 0.18 (uppercase `S` datasets from `kedro.extras`) and then tried to use Kedro 0.19 (no `kedro.extras` at all, need to install `kedro-datasets`), they would get an error, right?
  - I also reckon though that the versioning of `kedro-datasets` is not limited by `kedro_init_version`
  - In other words, how does this problem manifest itself nowadays? What sequence of steps gets us to here?
- It is well known that upgrading a Kedro version is hard in general (_but I could not locate an issue for it_). By looking at this problem from that angle, and considering that _clearly_ it arises from people not reading [our existing migration guides](https://docs.kedro.org/en/latest/resources/migration.html#dataset-renaming), can we provide linters ("`kedro-lint`") or semi-automatic migration utils ("`kedro-modernize`") to help with this task, rather than limiting ourselves to improving the traceback?

**Comment by ElenaKhaustova** [comment]
@astrojuanlu the blog post mentioned above: https://kedro.org/blog/add-kedro-to-your-data-science-notebook

**Comment by astrojuanlu** [comment]
Very good point about old training material using the old names, didn't think about that... This might be a problem that will need some time to go away then, and we might indeed need to take some action on our side.

**Comment by merelcht** [comment]
Looking at the error:

```
DatasetError: An exception occurred when parsing config for dataset 'companies':
Class 'pandas.CSVDataSet' not found, is this a typo?
```

I would still argue that the error isn't confusing, it states exactly what the problem is: spelling `DataSet` with a capital `S` instead of lower case `s`, which is indeed a typo. Now the question is whether we can add some additional clarification so that people check that lower/upper-case spelling. At the same time, it will be tricky to do specific matching for `DataSet` endings, because the user could have custom datasets that have that spelling and work fine.
